// Real Vulkan compute backend. Compiled only when QORVIX_ENABLE_VULKAN is ON and the Vulkan loader
// + a GLSL->SPIR-V compiler were found (see vulkan/CMakeLists.txt). Provides the same facade as the
// CUDA backend so the CLI/tests drive either without #ifdefs.
//
// Design: correctness-first, headless-verifiable. All buffers are HOST_VISIBLE|HOST_COHERENT so a
// dispatch is upload -> record -> submit -> wait -> read with no staging; this runs identically on
// Mesa's software device (lavapipe) — where the argmax-parity gate is checked with no physical GPU
// — and on real NVIDIA/AMD/Apple/Intel hardware (device-local + staging is a later throughput
// milestone, not a correctness one). The compute shaders are SPIR-V embedded at build time.
#include "qorvix/vulkan/backend.hpp"
#include "qorvix/vulkan/vulkan_model.hpp"

#include <vulkan/vulkan.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <functional>
#include <initializer_list>
#include <string>
#include <vector>

#include "qmatmul_q8_0_spv.h"  // const uint32_t qmatmul_q8_0_spv[] — generated by glslang
#include "qmatmul_q4_k_spv.h"  // const uint32_t qmatmul_q4_k_spv[]
#include "qmatmul_q6_k_spv.h"  // const uint32_t qmatmul_q6_k_spv[]
#include "rmsnorm_spv.h"       // const uint32_t rmsnorm_spv[]
#include "rope_spv.h"          // const uint32_t rope_spv[]
#include "swiglu_spv.h"        // const uint32_t swiglu_spv[]
#include "add_spv.h"           // const uint32_t add_spv[]
#include "attention_spv.h"     // const uint32_t attention_spv[]
#include "matmul_f32_spv.h"    // const uint32_t matmul_f32_spv[]
#include "embed_row_spv.h"     // const uint32_t embed_row_spv[]
#include "kv_store_spv.h"      // const uint32_t kv_store_spv[]

namespace qorvix::vulkan {
namespace {

// fp16 (IEEE half) <-> float, matching the GGUF scale encoding the shader decodes with
// unpackHalf2x16. Kept on the host so the reference and the shader agree bit-for-bit on the scale.
float decodeHalf(std::uint16_t h) {
  const std::uint32_t sign = (h & 0x8000u) << 16;
  const std::uint32_t exp = (h >> 10) & 0x1F;
  const std::uint32_t mant = h & 0x3FF;
  std::uint32_t bits;
  if (exp == 0) {
    if (mant == 0) {
      bits = sign;  // +/- zero
    } else {
      // subnormal half -> normalized float
      int e = -1;
      std::uint32_t m = mant;
      do {
        m <<= 1;
        ++e;
      } while ((m & 0x400u) == 0);
      m &= 0x3FFu;
      bits = sign | ((127 - 15 - e) << 23) | (m << 13);
    }
  } else if (exp == 0x1F) {
    bits = sign | 0x7F800000u | (mant << 13);  // inf/nan
  } else {
    bits = sign | ((exp - 15 + 127) << 23) | (mant << 13);
  }
  float f;
  std::memcpy(&f, &bits, 4);
  return f;
}

std::uint16_t encodeHalf(float f) {
  std::uint32_t x;
  std::memcpy(&x, &f, 4);
  const std::uint32_t sign = (x >> 16) & 0x8000u;
  std::int32_t exp = static_cast<std::int32_t>((x >> 23) & 0xFF) - 127 + 15;
  std::uint32_t mant = x & 0x7FFFFFu;
  if (exp <= 0) return static_cast<std::uint16_t>(sign);          // flush tiny to zero (sufficient here)
  if (exp >= 0x1F) return static_cast<std::uint16_t>(sign | 0x7C00u);  // overflow -> inf
  return static_cast<std::uint16_t>(sign | (exp << 10) | (mant >> 13));
}

// 6-bit (scale, min) unpack for sub-block j of a Q4_K scales array — the host mirror of the
// shader's getScaleMinK4 (verbatim from ggml), so the reference and the shader agree.
void getScaleMinK4(int j, const std::uint8_t* q, unsigned char& d, unsigned char& m) {
  if (j < 4) {
    d = q[j] & 63;
    m = q[j + 4] & 63;
  } else {
    d = (q[j + 4] & 0xF) | ((q[j - 4] >> 6) << 4);
    m = (q[j + 4] >> 4) | ((q[j] >> 6) << 4);
  }
}

// ---- minimal Vulkan compute context ---------------------------------------------------------
struct Context {
  VkInstance instance = VK_NULL_HANDLE;
  VkPhysicalDevice phys = VK_NULL_HANDLE;
  VkDevice device = VK_NULL_HANDLE;
  VkQueue queue = VK_NULL_HANDLE;
  std::uint32_t queueFamily = 0;
  VkCommandPool pool = VK_NULL_HANDLE;
  VkPhysicalDeviceMemoryProperties memProps{};
  bool ok = false;

  Context() = default;
  Context(const Context&) = delete;
  Context& operator=(const Context&) = delete;
  // Move by swap: the moved-from object is left holding our (null) handles, so its destructor frees
  // nothing. Lets a VulkanModel own its Context by value.
  Context(Context&& o) noexcept { swap(o); }
  Context& operator=(Context&& o) noexcept {
    if (this != &o) swap(o);
    return *this;
  }
  void swap(Context& o) noexcept {
    std::swap(instance, o.instance);
    std::swap(phys, o.phys);
    std::swap(device, o.device);
    std::swap(queue, o.queue);
    std::swap(queueFamily, o.queueFamily);
    std::swap(pool, o.pool);
    std::swap(memProps, o.memProps);
    std::swap(ok, o.ok);
  }

  ~Context() {
    if (device) {
      if (pool) vkDestroyCommandPool(device, pool, nullptr);
      vkDestroyDevice(device, nullptr);
    }
    if (instance) vkDestroyInstance(instance, nullptr);
  }
};

// Pick a queue family that supports compute.
bool findComputeQueue(VkPhysicalDevice phys, std::uint32_t& family) {
  std::uint32_t n = 0;
  vkGetPhysicalDeviceQueueFamilyProperties(phys, &n, nullptr);
  std::vector<VkQueueFamilyProperties> qf(n);
  vkGetPhysicalDeviceQueueFamilyProperties(phys, &n, qf.data());
  for (std::uint32_t i = 0; i < n; ++i) {
    if (qf[i].queueFlags & VK_QUEUE_COMPUTE_BIT) {
      family = i;
      return true;
    }
  }
  return false;
}

// Prefer a discrete GPU, then integrated, then anything (incl. the CPU software device).
VkPhysicalDevice pickPhysical(VkInstance inst) {
  std::uint32_t n = 0;
  vkEnumeratePhysicalDevices(inst, &n, nullptr);
  if (n == 0) return VK_NULL_HANDLE;
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(inst, &n, devs.data());
  VkPhysicalDevice best = VK_NULL_HANDLE;
  int bestRank = -1;
  for (auto d : devs) {
    VkPhysicalDeviceProperties p{};
    vkGetPhysicalDeviceProperties(d, &p);
    int rank = 0;
    switch (p.deviceType) {
      case VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU: rank = 4; break;
      case VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU: rank = 3; break;
      case VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU: rank = 2; break;
      case VK_PHYSICAL_DEVICE_TYPE_CPU: rank = 1; break;
      default: rank = 0; break;
    }
    std::uint32_t fam = 0;
    if (rank > bestRank && findComputeQueue(d, fam)) {
      best = d;
      bestRank = rank;
    }
  }
  return best;
}

Context makeContext() {
  Context c;
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.pApplicationName = "qorvix";
  app.apiVersion = VK_API_VERSION_1_1;

  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  if (vkCreateInstance(&ici, nullptr, &c.instance) != VK_SUCCESS) return c;

  c.phys = pickPhysical(c.instance);
  if (!c.phys) return c;
  if (!findComputeQueue(c.phys, c.queueFamily)) return c;
  vkGetPhysicalDeviceMemoryProperties(c.phys, &c.memProps);

  const float prio = 1.0f;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = c.queueFamily;
  qci.queueCount = 1;
  qci.pQueuePriorities = &prio;

  VkDeviceCreateInfo dci{};
  dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  dci.queueCreateInfoCount = 1;
  dci.pQueueCreateInfos = &qci;
  if (vkCreateDevice(c.phys, &dci, nullptr, &c.device) != VK_SUCCESS) return c;
  vkGetDeviceQueue(c.device, c.queueFamily, 0, &c.queue);

  VkCommandPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  pci.queueFamilyIndex = c.queueFamily;
  if (vkCreateCommandPool(c.device, &pci, nullptr, &c.pool) != VK_SUCCESS) return c;

  c.ok = true;
  return c;
}

std::uint32_t findMemType(const Context& c, std::uint32_t typeBits, VkMemoryPropertyFlags want) {
  for (std::uint32_t i = 0; i < c.memProps.memoryTypeCount; ++i) {
    if ((typeBits & (1u << i)) && (c.memProps.memoryTypes[i].propertyFlags & want) == want) return i;
  }
  return UINT32_MAX;
}

// A storage buffer. `hostVisible` ones are mapped directly; device-local ones are filled through a
// staging copy, which is the entire point of the distinction — see makeDeviceBuffer.
struct Buffer {
  VkDevice device = VK_NULL_HANDLE;
  VkBuffer buf = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  VkDeviceSize size = 0;
  bool hostVisible = true;

  void destroy() {
    if (buf) vkDestroyBuffer(device, buf, nullptr);
    if (mem) vkFreeMemory(device, mem, nullptr);
    buf = VK_NULL_HANDLE;
    mem = VK_NULL_HANDLE;
  }

  void zero() {
    if (!hostVisible) return;  // device-local buffers are zeroed with fillZero()
    void* p = nullptr;
    if (vkMapMemory(device, mem, 0, size, 0, &p) == VK_SUCCESS) {
      std::memset(p, 0, size);
      vkUnmapMemory(device, mem);
    }
  }
};

// Allocate + bind, given an exact memory-property requirement. Transfer bits are always on so any
// buffer can act as a staging source or a copy destination.
bool allocBuffer(const Context& c, VkDeviceSize size, VkMemoryPropertyFlags want, Buffer& out) {
  out.device = c.device;
  out.size = size;
  VkBufferCreateInfo bci{};
  bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bci.size = size;
  bci.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT |
              VK_BUFFER_USAGE_TRANSFER_DST_BIT;
  bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(c.device, &bci, nullptr, &out.buf) != VK_SUCCESS) return false;

  VkMemoryRequirements req{};
  vkGetBufferMemoryRequirements(c.device, out.buf, &req);
  const std::uint32_t mt = findMemType(c, req.memoryTypeBits, want);
  if (mt == UINT32_MAX) return false;
  out.hostVisible = (c.memProps.memoryTypes[mt].propertyFlags & VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) != 0;

  VkMemoryAllocateInfo mai{};
  mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  mai.allocationSize = req.size;
  mai.memoryTypeIndex = mt;
  if (vkAllocateMemory(c.device, &mai, nullptr, &out.mem) != VK_SUCCESS) return false;
  return vkBindBufferMemory(c.device, out.buf, out.mem, 0) == VK_SUCCESS;
}

// Host-visible + coherent: mappable from the CPU. Correct for anything the host touches per token
// (the logits readback) and for staging buffers.
bool makeBuffer(const Context& c, VkDeviceSize size, Buffer& out) {
  return allocBuffer(
      c, size, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT, out);
}

// DEVICE_LOCAL: real VRAM on a discrete GPU. Use for anything the GPU reads every token — above
// all the model weights.
//
// Why this exists: every buffer used to be allocated HOST_VISIBLE|HOST_COHERENT, which on a
// discrete GPU is SYSTEM RAM reached across PCIe, so each GEMV streamed the whole weight set over
// the bus once per token. That bug is INVISIBLE on the dev box's verification path: Mesa lavapipe
// reports exactly one memory type carrying DEVICE_LOCAL|HOST_VISIBLE|HOST_COHERENT|HOST_CACHED at
// once, so asking for host-visible there also happens to give you device-local. A discrete NVIDIA
// device exposes ~11 types and findMemType returns the FIRST host-visible one, which is host RAM.
// Hence: ask for what is actually wanted, and fall back only if the device has no device-local heap.
bool makeDeviceBuffer(const Context& c, VkDeviceSize size, Buffer& out) {
  if (allocBuffer(c, size, VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, out)) return true;
  out.destroy();
  return makeBuffer(c, size, out);
}

bool upload(const Buffer& b, const void* src, VkDeviceSize n) {
  void* p = nullptr;
  if (vkMapMemory(b.device, b.mem, 0, n, 0, &p) != VK_SUCCESS) return false;
  std::memcpy(p, src, n);
  vkUnmapMemory(b.device, b.mem);
  return true;
}

// Fill a device-local buffer through a temporary host-visible staging buffer. One-shot copy,
// synchronous, staging freed immediately — this runs at model load, never per token, so the cost is
// paid once and the peak extra host memory is one buffer's worth.
//
// Always staged, even when the destination happens to also be host-visible (integrated GPUs, and
// lavapipe). That is deliberate: it means the dev box's lavapipe run exercises exactly the code path
// a discrete GPU will take, instead of silently skipping it.
bool uploadDevice(const Context& c, const Buffer& dst, const void* src, VkDeviceSize n) {
  if (n == 0) return true;
  if (dst.hostVisible && !src) return true;

  Buffer stage{};
  if (!makeBuffer(c, n, stage)) {
    stage.destroy();
    return false;
  }
  if (!upload(stage, src, n)) {
    stage.destroy();
    return false;
  }

  VkCommandBufferAllocateInfo cbai{};
  cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  cbai.commandPool = c.pool;
  cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  cbai.commandBufferCount = 1;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  if (vkAllocateCommandBuffers(c.device, &cbai, &cmd) != VK_SUCCESS) {
    stage.destroy();
    return false;
  }

  VkCommandBufferBeginInfo bi{};
  bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
  bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
  vkBeginCommandBuffer(cmd, &bi);
  VkBufferCopy region{0, 0, n};
  vkCmdCopyBuffer(cmd, stage.buf, dst.buf, 1, &region);
  vkEndCommandBuffer(cmd);

  VkFenceCreateInfo fci{};
  fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
  VkFence fence = VK_NULL_HANDLE;
  bool ok = vkCreateFence(c.device, &fci, nullptr, &fence) == VK_SUCCESS;
  if (ok) {
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    ok = vkQueueSubmit(c.queue, 1, &si, fence) == VK_SUCCESS &&
         vkWaitForFences(c.device, 1, &fence, VK_TRUE, UINT64_MAX) == VK_SUCCESS;
    vkDestroyFence(c.device, fence, nullptr);
  }
  vkFreeCommandBuffers(c.device, c.pool, 1, &cmd);
  stage.destroy();
  return ok;
}

bool download(const Buffer& b, void* dst, VkDeviceSize n) {
  void* p = nullptr;
  if (vkMapMemory(b.device, b.mem, 0, n, 0, &p) != VK_SUCCESS) return false;
  std::memcpy(dst, p, n);
  vkUnmapMemory(b.device, b.mem);
  return true;
}

// One-shot compute pipeline over N storage-buffer bindings with a push-constant block. Builds the
// pipeline, dispatches `groups` workgroups, and waits. Returns false on any Vulkan error.
bool dispatch(const Context& c, const std::uint32_t* spirv, std::size_t spirvBytes,
              const std::vector<VkBuffer>& buffers, const void* push, std::uint32_t pushSize,
              std::uint32_t groups) {
  const std::uint32_t nb = static_cast<std::uint32_t>(buffers.size());

  std::vector<VkDescriptorSetLayoutBinding> binds(nb);
  for (std::uint32_t i = 0; i < nb; ++i) {
    binds[i] = {i, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};
  }
  VkDescriptorSetLayoutCreateInfo dslci{};
  dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  dslci.bindingCount = nb;
  dslci.pBindings = binds.data();
  VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
  if (vkCreateDescriptorSetLayout(c.device, &dslci, nullptr, &dsl) != VK_SUCCESS) return false;

  VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize};
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.setLayoutCount = 1;
  plci.pSetLayouts = &dsl;
  plci.pushConstantRangeCount = pushSize ? 1 : 0;
  plci.pPushConstantRanges = pushSize ? &pcr : nullptr;
  VkPipelineLayout layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(c.device, &plci, nullptr, &layout) != VK_SUCCESS) {
    vkDestroyDescriptorSetLayout(c.device, dsl, nullptr);
    return false;
  }

  VkShaderModuleCreateInfo smci{};
  smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  smci.codeSize = spirvBytes;
  smci.pCode = spirv;
  VkShaderModule shader = VK_NULL_HANDLE;
  bool okAll = false;
  VkPipeline pipe = VK_NULL_HANDLE;
  VkDescriptorPool descPool = VK_NULL_HANDLE;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  VkFence fence = VK_NULL_HANDLE;
  do {
    if (vkCreateShaderModule(c.device, &smci, nullptr, &shader) != VK_SUCCESS) break;

    VkPipelineShaderStageCreateInfo stage{};
    stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    stage.module = shader;
    stage.pName = "main";
    VkComputePipelineCreateInfo cpci{};
    cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage = stage;
    cpci.layout = layout;
    if (vkCreateComputePipelines(c.device, VK_NULL_HANDLE, 1, &cpci, nullptr, &pipe) != VK_SUCCESS)
      break;

    VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nb};
    VkDescriptorPoolCreateInfo dpci{};
    dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = 1;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(c.device, &dpci, nullptr, &descPool) != VK_SUCCESS) break;

    VkDescriptorSetAllocateInfo dsai{};
    dsai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    dsai.descriptorPool = descPool;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dsl;
    VkDescriptorSet set = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(c.device, &dsai, &set) != VK_SUCCESS) break;

    std::vector<VkDescriptorBufferInfo> dbi(nb);
    std::vector<VkWriteDescriptorSet> writes(nb);
    for (std::uint32_t i = 0; i < nb; ++i) {
      dbi[i] = {buffers[i], 0, VK_WHOLE_SIZE};
      writes[i] = {};
      writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
      writes[i].dstSet = set;
      writes[i].dstBinding = i;
      writes[i].descriptorCount = 1;
      writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
      writes[i].pBufferInfo = &dbi[i];
    }
    vkUpdateDescriptorSets(c.device, nb, writes.data(), 0, nullptr);

    VkCommandBufferAllocateInfo cbai{};
    cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    cbai.commandPool = c.pool;
    cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cbai.commandBufferCount = 1;
    if (vkAllocateCommandBuffers(c.device, &cbai, &cmd) != VK_SUCCESS) break;

    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipe);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layout, 0, 1, &set, 0, nullptr);
    if (pushSize) vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize, push);
    vkCmdDispatch(cmd, groups, 1, 1);
    vkEndCommandBuffer(cmd);

    VkFenceCreateInfo fci{};
    fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    if (vkCreateFence(c.device, &fci, nullptr, &fence) != VK_SUCCESS) break;
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    if (vkQueueSubmit(c.queue, 1, &si, fence) != VK_SUCCESS) break;
    if (vkWaitForFences(c.device, 1, &fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) break;
    okAll = true;
  } while (false);

  if (fence) vkDestroyFence(c.device, fence, nullptr);
  if (cmd) vkFreeCommandBuffers(c.device, c.pool, 1, &cmd);
  if (descPool) vkDestroyDescriptorPool(c.device, descPool, nullptr);
  if (pipe) vkDestroyPipeline(c.device, pipe, nullptr);
  if (shader) vkDestroyShaderModule(c.device, shader, nullptr);
  vkDestroyPipelineLayout(c.device, layout, nullptr);
  vkDestroyDescriptorSetLayout(c.device, dsl, nullptr);
  return okAll;
}

// ---- forward-pass orchestration (Milestone 4) -----------------------------------------------
// The per-op dispatch() above builds and tears down a pipeline every call — fine for one-shot self-
// tests, wrong for a forward pass that issues hundreds of dispatches. A `Pipe` is a compute pipeline
// built ONCE per shader and reused; a `Recorder` records many ops (each with a fresh descriptor set
// from a pool) into a single command buffer with a compute->compute barrier between them, so the
// whole forward is one submit. This is the reusable core the on-device model runner is built on.
struct Pipe {
  VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
  VkPipelineLayout layout = VK_NULL_HANDLE;
  VkPipeline pipe = VK_NULL_HANDLE;
  VkShaderModule mod = VK_NULL_HANDLE;
  std::uint32_t push = 0;
};

bool makePipe(const Context& c, const std::uint32_t* spv, std::size_t bytes, std::uint32_t nBindings,
              std::uint32_t pushSize, Pipe& out) {
  out.push = pushSize;
  std::vector<VkDescriptorSetLayoutBinding> binds(nBindings);
  for (std::uint32_t i = 0; i < nBindings; ++i)
    binds[i] = {i, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};
  VkDescriptorSetLayoutCreateInfo dslci{};
  dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  dslci.bindingCount = nBindings;
  dslci.pBindings = binds.data();
  if (vkCreateDescriptorSetLayout(c.device, &dslci, nullptr, &out.dsl) != VK_SUCCESS) return false;

  VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize};
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.setLayoutCount = 1;
  plci.pSetLayouts = &out.dsl;
  plci.pushConstantRangeCount = pushSize ? 1 : 0;
  plci.pPushConstantRanges = pushSize ? &pcr : nullptr;
  if (vkCreatePipelineLayout(c.device, &plci, nullptr, &out.layout) != VK_SUCCESS) return false;

  VkShaderModuleCreateInfo smci{};
  smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  smci.codeSize = bytes;
  smci.pCode = spv;
  if (vkCreateShaderModule(c.device, &smci, nullptr, &out.mod) != VK_SUCCESS) return false;

  VkPipelineShaderStageCreateInfo stage{};
  stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
  stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
  stage.module = out.mod;
  stage.pName = "main";
  VkComputePipelineCreateInfo cpci{};
  cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
  cpci.stage = stage;
  cpci.layout = out.layout;
  return vkCreateComputePipelines(c.device, VK_NULL_HANDLE, 1, &cpci, nullptr, &out.pipe) == VK_SUCCESS;
}

void destroyPipe(const Context& c, Pipe& p) {
  if (p.pipe) vkDestroyPipeline(c.device, p.pipe, nullptr);
  if (p.mod) vkDestroyShaderModule(c.device, p.mod, nullptr);
  if (p.layout) vkDestroyPipelineLayout(c.device, p.layout, nullptr);
  if (p.dsl) vkDestroyDescriptorSetLayout(c.device, p.dsl, nullptr);
  p = {};
}

struct Recorder {
  const Context& c;
  VkCommandBuffer cmd;
  VkDescriptorPool pool;
  bool ok = true;

  // Record one op: allocate+write a descriptor set for `bufs`, bind pipeline+set, push, dispatch,
  // then a full compute->compute barrier so the next op observes the writes.
  void op(const Pipe& p, std::initializer_list<VkBuffer> bufs, const void* push, std::uint32_t groups) {
    if (!ok) return;
    VkDescriptorSetAllocateInfo ai{};
    ai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    ai.descriptorPool = pool;
    ai.descriptorSetCount = 1;
    ai.pSetLayouts = &p.dsl;
    VkDescriptorSet set = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(c.device, &ai, &set) != VK_SUCCESS) {
      ok = false;
      return;
    }
    const std::uint32_t nb = static_cast<std::uint32_t>(bufs.size());
    std::vector<VkDescriptorBufferInfo> dbi(nb);
    std::vector<VkWriteDescriptorSet> wr(nb);
    std::uint32_t i = 0;
    for (VkBuffer b : bufs) {
      dbi[i] = {b, 0, VK_WHOLE_SIZE};
      wr[i] = {};
      wr[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
      wr[i].dstSet = set;
      wr[i].dstBinding = i;
      wr[i].descriptorCount = 1;
      wr[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
      wr[i].pBufferInfo = &dbi[i];
      ++i;
    }
    vkUpdateDescriptorSets(c.device, nb, wr.data(), 0, nullptr);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, p.pipe);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, p.layout, 0, 1, &set, 0, nullptr);
    if (p.push) vkCmdPushConstants(cmd, p.layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, p.push, push);
    vkCmdDispatch(cmd, groups, 1, 1);
    VkMemoryBarrier mb{};
    mb.sType = VK_STRUCTURE_TYPE_MEMORY_BARRIER;
    mb.srcAccessMask = VK_ACCESS_SHADER_WRITE_BIT;
    mb.dstAccessMask = VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT;
    vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                         0, 1, &mb, 0, nullptr, 0, nullptr);
  }
};

}  // namespace

bool builtWithVulkan() noexcept { return true; }

int deviceCount() {
  Context c = makeContext();
  return c.ok ? 1 : 0;  // one usable compute device (best pick); enumerateDevices() lists all
}

std::vector<DeviceInfo> enumerateDevices() {
  std::vector<DeviceInfo> out;
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.apiVersion = VK_API_VERSION_1_1;
  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  VkInstance inst = VK_NULL_HANDLE;
  if (vkCreateInstance(&ici, nullptr, &inst) != VK_SUCCESS) return out;

  std::uint32_t n = 0;
  vkEnumeratePhysicalDevices(inst, &n, nullptr);
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(inst, &n, devs.data());
  for (std::uint32_t i = 0; i < n; ++i) {
    VkPhysicalDeviceProperties p{};
    vkGetPhysicalDeviceProperties(devs[i], &p);
    VkPhysicalDeviceMemoryProperties mp{};
    vkGetPhysicalDeviceMemoryProperties(devs[i], &mp);
    std::size_t local = 0;
    for (std::uint32_t h = 0; h < mp.memoryHeapCount; ++h) {
      if (mp.memoryHeaps[h].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT)
        local = std::max<std::size_t>(local, mp.memoryHeaps[h].size);
    }
    DeviceInfo d;
    d.index = static_cast<int>(i);
    d.name = p.deviceName;
    d.apiVersion = p.apiVersion;
    d.vendorID = p.vendorID;
    d.deviceID = p.deviceID;
    d.deviceType = static_cast<int>(p.deviceType);
    d.deviceLocalMem = local;
    out.push_back(std::move(d));
  }
  vkDestroyInstance(inst, nullptr);
  return out;
}

std::optional<DeviceInfo> deviceInfo(int index) {
  auto all = enumerateDevices();
  for (auto& d : all)
    if (d.index == index) return d;
  return std::nullopt;
}

SelfTestResult selfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};

  VkPhysicalDeviceProperties p{};
  vkGetPhysicalDeviceProperties(c.phys, &p);

  // Bring-up: a trivial Q8_0 dispatch that must reproduce a hand-computed value. This exercises the
  // whole path — instance, device, queue, buffers, descriptors, pipeline, submit, readback — so a
  // green result means the compute plumbing works, not just that a device enumerated.
  const int rows = 1, cols = 32;
  std::vector<std::uint8_t> W(34, 0);
  const std::uint16_t hs = encodeHalf(0.5f);
  W[0] = static_cast<std::uint8_t>(hs & 0xFF);
  W[1] = static_cast<std::uint8_t>(hs >> 8);
  const float d = decodeHalf(hs);
  std::vector<float> x(cols), ref(rows, 0.0f);
  double acc = 0.0;
  for (int i = 0; i < cols; ++i) {
    const signed char q = static_cast<signed char>((i % 5) - 2);
    W[2 + i] = static_cast<std::uint8_t>(q);
    x[i] = 0.25f * ((i % 7) - 3);
    acc += d * static_cast<float>(q) * x[i];
  }
  ref[0] = static_cast<float>(acc);

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);  // pad to 4 for the uint[] SSBO
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const std::uint32_t groups = static_cast<std::uint32_t>(rows);  // one workgroup per output row
  const bool ran = dispatch(c, qmatmul_q8_0_spv, sizeof(qmatmul_q8_0_spv), {bw.buf, bx.buf, bo.buf},
                            &pc, sizeof(pc), groups);
  std::vector<float> got(rows, 0.0f);
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, "compute dispatch failed"};

  const float err = std::fabs(got[0] - ref[0]);
  if (err > 1e-3f)
    return {true, false, "compute result disagrees with host reference (err " + std::to_string(err) + ")"};
  return {true, true, std::string("compute pipeline OK on ") + p.deviceName};
}

SelfTestResult qmatmulQ8_0SelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  // ---- correctness on a small Q8_0 matrix vs a host reference (mirrors the CUDA self-test) ----
  const int rows = 64, cols = 256;
  const int nBlocks = cols / 32;
  const std::size_t rowBytes = static_cast<std::size_t>(nBlocks) * 34;
  std::vector<std::uint8_t> W(static_cast<std::size_t>(rows) * rowBytes, 0);
  std::vector<float> x(cols), ref(rows, 0.0f), got(rows, 0.0f);
  for (int i = 0; i < cols; ++i) x[i] = 0.1f * ((i % 5) - 2);
  for (int r = 0; r < rows; ++r) {
    double acc = 0.0;
    for (int b = 0; b < nBlocks; ++b) {
      std::uint8_t* blk = W.data() + static_cast<std::size_t>(r) * rowBytes + static_cast<std::size_t>(b) * 34;
      const std::uint16_t hs = encodeHalf(0.02f * ((r % 7) + 1));
      blk[0] = static_cast<std::uint8_t>(hs & 0xFF);
      blk[1] = static_cast<std::uint8_t>(hs >> 8);
      const float d = decodeHalf(hs);  // rounded scale so the reference matches the shader
      for (int i = 0; i < 32; ++i) {
        const signed char q = static_cast<signed char>(((r + b + i) % 15) - 7);
        blk[2 + i] = static_cast<std::uint8_t>(q);
        acc += d * static_cast<float>(q) * x[b * 32 + i];
      }
    }
    ref[r] = static_cast<float>(acc);
  }

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const bool ran = dispatch(c, qmatmul_q8_0_spv, sizeof(qmatmul_q8_0_spv), {bw.buf, bx.buf, bo.buf},
                            &pc, sizeof(pc), static_cast<std::uint32_t>(rows));
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, "qmatmul dispatch failed"};

  float maxErr = 0.0f;
  for (int r = 0; r < rows; ++r) maxErr = std::max(maxErr, std::fabs(got[r] - ref[r]));
  if (maxErr > 1e-2f)
    return {true, false, "Vulkan qmatmul disagrees with host reference (max err " +
                             std::to_string(maxErr) + ")"};

  return {true, true, std::string("Vulkan Q8_0 matmul matches host reference (max err ") +
                          std::to_string(maxErr) + ") on " + dp.deviceName};
}

// Shared driver for a K-quant (Q4_K / Q6_K) GEMV self-test: builds a synthetic weight matrix and a
// host reference with `ref`, runs `spirv` on the device, and compares. `blockBytes` is the super-
// block size (144 for Q4_K, 210 for Q6_K), `fill` populates one super-block's bytes given (r, sb).
SelfTestResult kQuantSelfTest(const char* label, const std::uint32_t* spirv, std::size_t spirvBytes,
                              int blockBytes,
                              const std::function<void(int r, int sb, std::uint8_t* blk,
                                                       const std::vector<float>& x, double& acc)>& fill) {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  const int rows = 48, cols = 512;  // 2 super-blocks/row
  const int nSB = cols / 256;
  const std::size_t rowBytes = static_cast<std::size_t>(nSB) * blockBytes;
  std::vector<std::uint8_t> W(static_cast<std::size_t>(rows) * rowBytes, 0);
  std::vector<float> x(cols), ref(rows, 0.0f), got(rows, 0.0f);
  for (int i = 0; i < cols; ++i) x[i] = 0.05f * ((i % 13) - 6);
  for (int r = 0; r < rows; ++r) {
    double acc = 0.0;
    for (int sb = 0; sb < nSB; ++sb) {
      std::uint8_t* blk = W.data() + static_cast<std::size_t>(r) * rowBytes +
                          static_cast<std::size_t>(sb) * blockBytes;
      fill(r, sb, blk, x, acc);
    }
    ref[r] = static_cast<float>(acc);
  }

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const bool ran =
      dispatch(c, spirv, spirvBytes, {bw.buf, bx.buf, bo.buf}, &pc, sizeof(pc), static_cast<std::uint32_t>(rows));
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, std::string(label) + " dispatch failed"};

  float maxErr = 0.0f, ref2 = 0.0f;
  for (int r = 0; r < rows; ++r) {
    maxErr = std::max(maxErr, std::fabs(got[r] - ref[r]));
    ref2 = std::max(ref2, std::fabs(ref[r]));
  }
  const float tol = 1e-2f * (1.0f + ref2);  // scale tolerance to the magnitude of the reference
  if (maxErr > tol)
    return {true, false, std::string(label) + " disagrees with host reference (max err " +
                             std::to_string(maxErr) + ")"};
  return {true, true, std::string(label) + " matches host reference (max err " +
                          std::to_string(maxErr) + ") on " + dp.deviceName};
}

SelfTestResult qmatmulQ4_KSelfTest() {
  return kQuantSelfTest(
      "Vulkan Q4_K matmul", qmatmul_q4_k_spv, sizeof(qmatmul_q4_k_spv), 144,
      [](int r, int sb, std::uint8_t* blk, const std::vector<float>& x, double& acc) {
        const std::uint16_t dh = encodeHalf(0.015f * ((r % 5) + 1));
        const std::uint16_t mh = encodeHalf(0.007f * ((sb % 3) + 1));
        blk[0] = dh & 0xFF;
        blk[1] = dh >> 8;
        blk[2] = mh & 0xFF;
        blk[3] = mh >> 8;
        for (int i = 0; i < 12; ++i) blk[4 + i] = static_cast<std::uint8_t>((r * 7 + sb * 3 + i * 11) & 0x3F);
        std::uint8_t* qs = blk + 16;
        for (int i = 0; i < 128; ++i) qs[i] = static_cast<std::uint8_t>((r + sb + i * 5) & 0xFF);
        const float d = decodeHalf(dh), dmin = decodeHalf(mh);
        for (int j = 0; j < 8; ++j) {
          unsigned char sc, m;
          getScaleMinK4(j, blk + 4, sc, m);
          for (int t = 0; t < 32; ++t) {
            const int i = j * 32 + t;
            const int chunk = i / 64, local = i % 64;
            const std::uint8_t qbyte = qs[chunk * 32 + (local & 31)];
            const int nib = (local < 32) ? (qbyte & 0xF) : (qbyte >> 4);
            acc += (d * sc * nib - dmin * m) * x[static_cast<std::size_t>(sb) * 256 + i];
          }
        }
      });
}

SelfTestResult qmatmulQ6_KSelfTest() {
  return kQuantSelfTest(
      "Vulkan Q6_K matmul", qmatmul_q6_k_spv, sizeof(qmatmul_q6_k_spv), 210,
      [](int r, int sb, std::uint8_t* blk, const std::vector<float>& x, double& acc) {
        std::uint8_t* ql = blk;
        std::uint8_t* qh = blk + 128;
        signed char* sc = reinterpret_cast<signed char*>(blk + 192);
        for (int i = 0; i < 128; ++i) ql[i] = static_cast<std::uint8_t>((r + sb + i * 3) & 0xFF);
        for (int i = 0; i < 64; ++i) qh[i] = static_cast<std::uint8_t>((r * 2 + sb + i * 7) & 0xFF);
        for (int i = 0; i < 16; ++i) sc[i] = static_cast<signed char>(((r + sb + i * 5) % 25) - 12);
        const std::uint16_t dh = encodeHalf(0.012f * ((r % 6) + 1));
        blk[208] = dh & 0xFF;
        blk[209] = dh >> 8;
        const float d = decodeHalf(dh);
        for (int i = 0; i < 256; ++i) {
          const int hlf = i >> 7, p = i & 127, l = p & 31, quarter = p >> 5, isub = l >> 4;
          const std::uint8_t* qlh = ql + hlf * 64;
          const std::uint8_t* qhh = qh + hlf * 32;
          int lo, hi;
          if (quarter == 0) { lo = qlh[l] & 0xF;      hi = (qhh[l] >> 0) & 3; }
          else if (quarter == 1) { lo = qlh[l + 32] & 0xF; hi = (qhh[l] >> 2) & 3; }
          else if (quarter == 2) { lo = qlh[l] >> 4;   hi = (qhh[l] >> 4) & 3; }
          else { lo = qlh[l + 32] >> 4;                hi = (qhh[l] >> 6) & 3; }
          const int q = (lo | (hi << 4)) - 32;
          const int scv = sc[hlf * 8 + isub + quarter * 2];
          acc += d * scv * q * x[static_cast<std::size_t>(sb) * 256 + i];
        }
      });
}

SelfTestResult opsSelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  float maxErr = 0.0f;
  auto track = [&](const std::vector<float>& a, const std::vector<float>& b) {
    for (std::size_t i = 0; i < a.size(); ++i) maxErr = std::max(maxErr, std::fabs(a[i] - b[i]));
  };
  const char* failed = nullptr;

  // RMSNorm: bindings {out, x, w}, one workgroup.
  {
    const int n = 512;
    std::vector<float> x(n), w(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) {
      x[i] = 0.01f * ((i % 13) - 6);
      w[i] = 0.5f + 0.001f * i;
    }
    double sq = 0.0;
    for (float v : x) sq += static_cast<double>(v) * v;
    const float scale = 1.0f / std::sqrt(static_cast<float>(sq / n) + 1e-5f);
    for (int i = 0; i < n; ++i) ref[i] = x[i] * scale * w[i];
    Buffer bo{}, bx{}, bw{};
    if (makeBuffer(c, n * sizeof(float), bo) && makeBuffer(c, n * sizeof(float), bx) &&
        makeBuffer(c, n * sizeof(float), bw)) {
      upload(bx, x.data(), n * sizeof(float));
      upload(bw, w.data(), n * sizeof(float));
      struct {
        std::uint32_t n;
        float eps;
      } pc{static_cast<std::uint32_t>(n), 1e-5f};
      if (dispatch(c, rmsnorm_spv, sizeof(rmsnorm_spv), {bo.buf, bx.buf, bw.buf}, &pc, sizeof(pc), 1)) {
        download(bo, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "rmsnorm";
      }
    } else {
      failed = "rmsnorm alloc";
    }
    bo.destroy();
    bx.destroy();
    bw.destroy();
  }

  // RoPE (NeoX): binding {v} in place.
  if (!failed) {
    const int nH = 4, hd = 8, half = hd / 2, pos = 3, n = nH * hd;
    const float base = 10000.0f;
    std::vector<float> v(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) v[i] = 0.1f * ((i % 7) - 3);
    ref = v;
    for (int h = 0; h < nH; ++h)
      for (int i = 0; i < half; ++i) {
        const float theta = pos * std::pow(base, -2.0f * i / hd);
        const float cc = std::cos(theta), ss = std::sin(theta);
        const float a = ref[h * hd + i], b = ref[h * hd + i + half];
        ref[h * hd + i] = a * cc - b * ss;
        ref[h * hd + i + half] = a * ss + b * cc;
      }
    Buffer bv{};
    if (makeBuffer(c, n * sizeof(float), bv)) {
      upload(bv, v.data(), n * sizeof(float));
      struct {
        std::uint32_t nHeads, headDim;
        std::int32_t pos;
        float freqBase;
      } pc{static_cast<std::uint32_t>(nH), static_cast<std::uint32_t>(hd), pos, base};
      if (dispatch(c, rope_spv, sizeof(rope_spv), {bv.buf}, &pc, sizeof(pc),
                   static_cast<std::uint32_t>((nH * half + 63) / 64))) {
        download(bv, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "rope";
      }
    } else {
      failed = "rope alloc";
    }
    bv.destroy();
  }

  // SwiGLU: bindings {out, gate, up}.
  if (!failed) {
    const int n = 1000;
    std::vector<float> g(n), u(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) {
      g[i] = 0.02f * ((i % 11) - 5);
      u[i] = 0.03f * ((i % 9) - 4);
      ref[i] = (g[i] / (1.0f + std::exp(-g[i]))) * u[i];
    }
    Buffer bo{}, bg{}, bu{};
    if (makeBuffer(c, n * sizeof(float), bo) && makeBuffer(c, n * sizeof(float), bg) &&
        makeBuffer(c, n * sizeof(float), bu)) {
      upload(bg, g.data(), n * sizeof(float));
      upload(bu, u.data(), n * sizeof(float));
      struct {
        std::uint32_t n;
      } pc{static_cast<std::uint32_t>(n)};
      if (dispatch(c, swiglu_spv, sizeof(swiglu_spv), {bo.buf, bg.buf, bu.buf}, &pc, sizeof(pc),
                   static_cast<std::uint32_t>((n + 255) / 256))) {
        download(bo, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "swiglu";
      }
    } else {
      failed = "swiglu alloc";
    }
    bo.destroy();
    bg.destroy();
    bu.destroy();
  }

  // Residual add: binding {out(=a, in place), x(=b)}.
  if (!failed) {
    const int n = 1000;
    std::vector<float> a(n), b(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) {
      a[i] = 0.1f * i;
      b[i] = -0.05f * i;
      ref[i] = a[i] + b[i];
    }
    Buffer ba{}, bb{};
    if (makeBuffer(c, n * sizeof(float), ba) && makeBuffer(c, n * sizeof(float), bb)) {
      upload(ba, a.data(), n * sizeof(float));
      upload(bb, b.data(), n * sizeof(float));
      struct {
        std::uint32_t n;
      } pc{static_cast<std::uint32_t>(n)};
      if (dispatch(c, add_spv, sizeof(add_spv), {ba.buf, bb.buf}, &pc, sizeof(pc),
                   static_cast<std::uint32_t>((n + 255) / 256))) {
        download(ba, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "add";
      }
    } else {
      failed = "add alloc";
    }
    ba.destroy();
    bb.destroy();
  }

  if (failed) return {true, false, std::string(failed) + " dispatch failed"};
  const bool ok = maxErr < 1e-3f;
  return {true, ok,
          (ok ? "rmsnorm/rope/swiglu/add match CPU (max err " : "Vulkan ops disagree with CPU (max err ") +
              std::to_string(maxErr) + ") on " + dp.deviceName};
}

SelfTestResult attentionSelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  // GQA: 4 query heads, 2 kv heads, head_dim 8, 5 cached positions (matches the CUDA self-test).
  const int nHeads = 4, nKv = 2, headDim = 8, seqLen = 5;
  const int kvDim = nKv * headDim;
  const int group = nHeads / nKv;
  std::vector<float> q(static_cast<std::size_t>(nHeads) * headDim);
  std::vector<float> K(static_cast<std::size_t>(seqLen) * kvDim);
  std::vector<float> V(static_cast<std::size_t>(seqLen) * kvDim);
  for (std::size_t i = 0; i < q.size(); ++i) q[i] = 0.05f * ((i % 11) - 5);
  for (std::size_t i = 0; i < K.size(); ++i) K[i] = 0.03f * ((i % 13) - 6);
  for (std::size_t i = 0; i < V.size(); ++i) V[i] = 0.04f * ((i % 7) - 3);

  std::vector<float> ref(static_cast<std::size_t>(nHeads) * headDim, 0.0f), got(ref.size());
  const float invSqrt = 1.0f / std::sqrt(static_cast<float>(headDim));
  for (int h = 0; h < nHeads; ++h) {
    const int kvHead = h / group;
    std::vector<float> sc(seqLen);
    for (int t = 0; t < seqLen; ++t) {
      float dot = 0.0f;
      for (int d = 0; d < headDim; ++d)
        dot += q[h * headDim + d] * K[t * kvDim + kvHead * headDim + d];
      sc[t] = dot * invSqrt;
    }
    float mx = sc[0];
    for (int t = 1; t < seqLen; ++t) mx = std::max(mx, sc[t]);
    float sum = 0.0f;
    for (int t = 0; t < seqLen; ++t) {
      sc[t] = std::exp(sc[t] - mx);
      sum += sc[t];
    }
    for (int d = 0; d < headDim; ++d) {
      float acc = 0.0f;
      for (int t = 0; t < seqLen; ++t)
        acc += (sc[t] / sum) * V[t * kvDim + kvHead * headDim + d];
      ref[h * headDim + d] = acc;
    }
  }

  Buffer bo{}, bq{}, bk{}, bv{};
  if (!makeBuffer(c, got.size() * sizeof(float), bo) || !makeBuffer(c, q.size() * sizeof(float), bq) ||
      !makeBuffer(c, K.size() * sizeof(float), bk) || !makeBuffer(c, V.size() * sizeof(float), bv)) {
    bo.destroy();
    bq.destroy();
    bk.destroy();
    bv.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bq, q.data(), q.size() * sizeof(float));
  upload(bk, K.data(), K.size() * sizeof(float));
  upload(bv, V.data(), V.size() * sizeof(float));
  struct {
    std::uint32_t nHeads, nKv, headDim, seqLen, kvDim, layer, maxSeq;
  } pc{static_cast<std::uint32_t>(nHeads), static_cast<std::uint32_t>(nKv),
       static_cast<std::uint32_t>(headDim), static_cast<std::uint32_t>(seqLen),
       static_cast<std::uint32_t>(kvDim), 0u, static_cast<std::uint32_t>(seqLen)};
  const bool ran = dispatch(c, attention_spv, sizeof(attention_spv), {bo.buf, bq.buf, bk.buf, bv.buf},
                            &pc, sizeof(pc), static_cast<std::uint32_t>(nHeads));
  if (ran) download(bo, got.data(), got.size() * sizeof(float));
  bo.destroy();
  bq.destroy();
  bk.destroy();
  bv.destroy();
  if (!ran) return {true, false, "attention dispatch failed"};

  float maxErr = 0.0f;
  for (std::size_t i = 0; i < ref.size(); ++i) maxErr = std::max(maxErr, std::fabs(got[i] - ref[i]));
  const bool ok = maxErr < 1e-3f;
  return {true, ok,
          (ok ? "GQA decode attention matches CPU (max err " : "attention disagrees with CPU (max err ") +
              std::to_string(maxErr) + ") on " + dp.deviceName};
}

SelfTestResult forwardSelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  // Tiny synthetic Llama-style model — identical shape/values to gpuForwardSelfTest so both backends
  // are checked against the same reference.
  const int L = 2, d = 32, nHeads = 4, headDim = 8, nKv = 2, ffn = 64, vocab = 16, maxSeq = 8;
  const int kvDim = nKv * headDim, qDim = nHeads * headDim, group = nHeads / nKv;
  const float eps = 1e-5f, freqBase = 10000.0f;
  auto gen = [](int seed, int i) { return 0.01f * (((i * 7 + seed * 13) % 17) - 8); };

  std::vector<float> tokEmbd(vocab * d), outNorm(d, 1.0f), output(vocab * d);
  for (int i = 0; i < vocab * d; ++i) tokEmbd[i] = gen(1, i);
  for (int i = 0; i < vocab * d; ++i) output[i] = gen(2, i);
  for (int i = 0; i < d; ++i) outNorm[i] = 1.0f + 0.01f * i;
  struct Layer {
    std::vector<float> attnNorm, wq, wk, wv, wo, ffnNorm, ffnGate, ffnUp, ffnDown;
  };
  std::vector<Layer> lw(L);
  for (int l = 0; l < L; ++l) {
    Layer& w = lw[l];
    w.attnNorm.assign(d, 0.0f);
    w.ffnNorm.assign(d, 0.0f);
    for (int i = 0; i < d; ++i) {
      w.attnNorm[i] = 1.0f + 0.01f * ((i + l) % 5);
      w.ffnNorm[i] = 1.0f + 0.01f * ((i + l) % 3);
    }
    w.wq.resize(qDim * d);
    w.wo.resize(d * qDim);
    w.wk.resize(kvDim * d);
    w.wv.resize(kvDim * d);
    w.ffnGate.resize(ffn * d);
    w.ffnUp.resize(ffn * d);
    w.ffnDown.resize(d * ffn);
    for (int i = 0; i < qDim * d; ++i) w.wq[i] = gen(10 + l, i);
    for (int i = 0; i < d * qDim; ++i) w.wo[i] = gen(20 + l, i);
    for (int i = 0; i < kvDim * d; ++i) w.wk[i] = gen(30 + l, i);
    for (int i = 0; i < kvDim * d; ++i) w.wv[i] = gen(40 + l, i);
    for (int i = 0; i < ffn * d; ++i) w.ffnGate[i] = gen(50 + l, i);
    for (int i = 0; i < ffn * d; ++i) w.ffnUp[i] = gen(60 + l, i);
    for (int i = 0; i < d * ffn; ++i) w.ffnDown[i] = gen(70 + l, i);
  }

  // ---- inline CPU reference (mirrors runtime/TextModel and gpuForwardSelfTest's cpuForward) ----
  auto rms = [&](std::vector<float>& o, const std::vector<float>& x, const std::vector<float>& w, int n) {
    double sq = 0.0;
    for (int i = 0; i < n; ++i) sq += static_cast<double>(x[i]) * x[i];
    const float sc = 1.0f / std::sqrt(static_cast<float>(sq / n) + eps);
    for (int i = 0; i < n; ++i) o[i] = x[i] * sc * w[i];
  };
  auto mm = [&](std::vector<float>& o, const std::vector<float>& W, const std::vector<float>& x, int rows, int cols) {
    for (int r = 0; r < rows; ++r) {
      double a = 0.0;
      for (int cc = 0; cc < cols; ++cc) a += static_cast<double>(W[r * cols + cc]) * x[cc];
      o[r] = static_cast<float>(a);
    }
  };
  auto ropeRef = [&](std::vector<float>& v, int nh, int pos) {
    const int half = headDim / 2;
    for (int h = 0; h < nh; ++h)
      for (int i = 0; i < half; ++i) {
        const float th = pos * std::pow(freqBase, -2.0f * i / headDim);
        const float cc = std::cos(th), ss = std::sin(th);
        const float a = v[h * headDim + i], b = v[h * headDim + i + half];
        v[h * headDim + i] = a * cc - b * ss;
        v[h * headDim + i + half] = a * ss + b * cc;
      }
  };
  std::vector<float> hKc(static_cast<std::size_t>(L) * maxSeq * kvDim, 0.0f), hVc = hKc;
  auto cpuForward = [&](int token, int pos, std::vector<float>& logits) {
    std::vector<float> x(tokEmbd.begin() + token * d, tokEmbd.begin() + token * d + d);
    std::vector<float> xn(d), q(qDim), k(kvDim), v(kvDim), attn(qDim), tmp(d), g(ffn), u(ffn), act(ffn);
    for (int l = 0; l < L; ++l) {
      Layer& w = lw[l];
      rms(xn, x, w.attnNorm, d);
      mm(q, w.wq, xn, qDim, d);
      mm(k, w.wk, xn, kvDim, d);
      mm(v, w.wv, xn, kvDim, d);
      ropeRef(q, nHeads, pos);
      ropeRef(k, nKv, pos);
      for (int i = 0; i < kvDim; ++i) {
        hKc[(static_cast<std::size_t>(l) * maxSeq + pos) * kvDim + i] = k[i];
        hVc[(static_cast<std::size_t>(l) * maxSeq + pos) * kvDim + i] = v[i];
      }
      const float invSqrt = 1.0f / std::sqrt(static_cast<float>(headDim));
      for (int h = 0; h < nHeads; ++h) {
        const int kvHead = h / group;
        std::vector<float> sc(pos + 1);
        for (int t = 0; t <= pos; ++t) {
          float dot = 0.0f;
          for (int e = 0; e < headDim; ++e)
            dot += q[h * headDim + e] * hKc[(static_cast<std::size_t>(l) * maxSeq + t) * kvDim + kvHead * headDim + e];
          sc[t] = dot * invSqrt;
        }
        float mx = sc[0];
        for (int t = 1; t <= pos; ++t) mx = std::max(mx, sc[t]);
        float sum = 0.0f;
        for (int t = 0; t <= pos; ++t) {
          sc[t] = std::exp(sc[t] - mx);
          sum += sc[t];
        }
        for (int e = 0; e < headDim; ++e) {
          float a = 0.0f;
          for (int t = 0; t <= pos; ++t)
            a += (sc[t] / sum) * hVc[(static_cast<std::size_t>(l) * maxSeq + t) * kvDim + kvHead * headDim + e];
          attn[h * headDim + e] = a;
        }
      }
      mm(tmp, w.wo, attn, d, qDim);
      for (int i = 0; i < d; ++i) x[i] += tmp[i];
      rms(xn, x, w.ffnNorm, d);
      mm(g, w.ffnGate, xn, ffn, d);
      mm(u, w.ffnUp, xn, ffn, d);
      for (int i = 0; i < ffn; ++i) act[i] = (g[i] / (1.0f + std::exp(-g[i]))) * u[i];
      mm(tmp, w.ffnDown, act, d, ffn);
      for (int i = 0; i < d; ++i) x[i] += tmp[i];
    }
    rms(xn, x, outNorm, d);
    logits.resize(vocab);
    mm(logits, output, xn, vocab, d);
  };

  // ---- build pipelines once ----
  Pipe pEmbed{}, pMatmul{}, pRms{}, pRope{}, pKv{}, pAttn{}, pSwiglu{}, pAdd{};
  bool pipesOk = makePipe(c, embed_row_spv, sizeof(embed_row_spv), 2, 8, pEmbed) &&
                 makePipe(c, matmul_f32_spv, sizeof(matmul_f32_spv), 3, 8, pMatmul) &&
                 makePipe(c, rmsnorm_spv, sizeof(rmsnorm_spv), 3, 8, pRms) &&
                 makePipe(c, rope_spv, sizeof(rope_spv), 1, 16, pRope) &&
                 makePipe(c, kv_store_spv, sizeof(kv_store_spv), 2, 16, pKv) &&
                 makePipe(c, attention_spv, sizeof(attention_spv), 4, 28, pAttn) &&
                 makePipe(c, swiglu_spv, sizeof(swiglu_spv), 3, 4, pSwiglu) &&
                 makePipe(c, add_spv, sizeof(add_spv), 2, 4, pAdd);

  // ---- device buffers ----
  std::vector<Buffer> owned;
  bool allocOk = true;
  auto mkBytes = [&](VkDeviceSize bytes, const void* src, VkDeviceSize srcBytes) -> VkBuffer {
    Buffer b{};
    if (!makeBuffer(c, bytes, b)) {
      allocOk = false;
      return VK_NULL_HANDLE;
    }
    if (src) upload(b, src, srcBytes);
    owned.push_back(b);
    return owned.back().buf;
  };
  auto mkF = [&](const std::vector<float>& v) {
    return mkBytes(v.size() * sizeof(float), v.data(), v.size() * sizeof(float));
  };
  auto mkScratch = [&](int n) { return mkBytes(static_cast<VkDeviceSize>(n) * sizeof(float), nullptr, 0); };

  VkBuffer bTok = mkF(tokEmbd), bOutNorm = mkF(outNorm), bOutput = mkF(output);
  std::vector<VkBuffer> bAttnN(L), bFfnN(L), bWq(L), bWk(L), bWv(L), bWo(L), bGate(L), bUp(L), bDown(L);
  for (int l = 0; l < L; ++l) {
    bAttnN[l] = mkF(lw[l].attnNorm);
    bFfnN[l] = mkF(lw[l].ffnNorm);
    bWq[l] = mkF(lw[l].wq);
    bWk[l] = mkF(lw[l].wk);
    bWv[l] = mkF(lw[l].wv);
    bWo[l] = mkF(lw[l].wo);
    bGate[l] = mkF(lw[l].ffnGate);
    bUp[l] = mkF(lw[l].ffnUp);
    bDown[l] = mkF(lw[l].ffnDown);
  }
  std::vector<float> zeroKv(static_cast<std::size_t>(L) * maxSeq * kvDim, 0.0f);
  VkBuffer bKc = mkF(zeroKv), bVc = mkF(zeroKv);
  VkBuffer bx = mkScratch(d), bxn = mkScratch(d), bq = mkScratch(qDim), bk = mkScratch(kvDim),
           bv = mkScratch(kvDim), battn = mkScratch(qDim), btmp = mkScratch(d), bg = mkScratch(ffn),
           bu = mkScratch(ffn), bact = mkScratch(ffn), blogits = mkScratch(vocab);

  // ---- command buffer + fence + descriptor pool ----
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  VkCommandBufferAllocateInfo cbai{};
  cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
  cbai.commandPool = c.pool;
  cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
  cbai.commandBufferCount = 1;
  VkFence fence = VK_NULL_HANDLE;
  VkFenceCreateInfo fci{};
  fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
  VkDescriptorPoolSize dps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 512};
  VkDescriptorPoolCreateInfo dpci{};
  dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
  dpci.maxSets = 128;
  dpci.poolSizeCount = 1;
  dpci.pPoolSizes = &dps;
  VkDescriptorPool descPool = VK_NULL_HANDLE;
  const bool infraOk = pipesOk && allocOk &&
                       vkAllocateCommandBuffers(c.device, &cbai, &cmd) == VK_SUCCESS &&
                       vkCreateFence(c.device, &fci, nullptr, &fence) == VK_SUCCESS &&
                       vkCreateDescriptorPool(c.device, &dpci, nullptr, &descPool) == VK_SUCCESS;

  const int tokens[3] = {1, 5, 9};
  auto g256 = [](int n) { return static_cast<std::uint32_t>((n + 255) / 256); };
  float maxErr = 0.0f;
  bool ran = infraOk;

  for (int pos = 0; pos < 3 && ran; ++pos) {
    vkResetDescriptorPool(c.device, descPool, 0);
    vkResetCommandBuffer(cmd, 0);
    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);

    Recorder rec{c, cmd, descPool};
    struct EmbedPC { std::uint32_t token, d; } ePC{static_cast<std::uint32_t>(tokens[pos]), (std::uint32_t)d};
    rec.op(pEmbed, {bx, bTok}, &ePC, g256(d));
    for (int l = 0; l < L; ++l) {
      struct RmsPC { std::uint32_t n; float eps; };
      struct MmPC { std::uint32_t rows, cols; };
      struct RopePC { std::uint32_t nh, hd; std::int32_t pos; float base; };
      struct KvPC { std::uint32_t layer, pos, maxSeq, kvDim; };
      struct AttnPC { std::uint32_t nHeads, nKv, headDim, seqLen, kvDim, layer, maxSeq; };
      struct NPC { std::uint32_t n; };
      RmsPC a1{(std::uint32_t)d, eps};
      rec.op(pRms, {bxn, bx, bAttnN[l]}, &a1, 1);
      MmPC mq{(std::uint32_t)qDim, (std::uint32_t)d}, mkv{(std::uint32_t)kvDim, (std::uint32_t)d};
      rec.op(pMatmul, {bq, bWq[l], bxn}, &mq, (std::uint32_t)qDim);
      rec.op(pMatmul, {bk, bWk[l], bxn}, &mkv, (std::uint32_t)kvDim);
      rec.op(pMatmul, {bv, bWv[l], bxn}, &mkv, (std::uint32_t)kvDim);
      RopePC rq{(std::uint32_t)nHeads, (std::uint32_t)headDim, pos, freqBase},
          rk{(std::uint32_t)nKv, (std::uint32_t)headDim, pos, freqBase};
      rec.op(pRope, {bq}, &rq, static_cast<std::uint32_t>((nHeads * headDim / 2 + 63) / 64));
      rec.op(pRope, {bk}, &rk, static_cast<std::uint32_t>((nKv * headDim / 2 + 63) / 64));
      KvPC kv{(std::uint32_t)l, (std::uint32_t)pos, (std::uint32_t)maxSeq, (std::uint32_t)kvDim};
      rec.op(pKv, {bKc, bk}, &kv, g256(kvDim));
      rec.op(pKv, {bVc, bv}, &kv, g256(kvDim));
      AttnPC ap{(std::uint32_t)nHeads, (std::uint32_t)nKv, (std::uint32_t)headDim,
                (std::uint32_t)(pos + 1), (std::uint32_t)kvDim, (std::uint32_t)l, (std::uint32_t)maxSeq};
      rec.op(pAttn, {battn, bq, bKc, bVc}, &ap, (std::uint32_t)nHeads);
      MmPC mo{(std::uint32_t)d, (std::uint32_t)qDim};
      rec.op(pMatmul, {btmp, bWo[l], battn}, &mo, (std::uint32_t)d);
      NPC nd{(std::uint32_t)d};
      rec.op(pAdd, {bx, btmp}, &nd, g256(d));
      RmsPC a2{(std::uint32_t)d, eps};
      rec.op(pRms, {bxn, bx, bFfnN[l]}, &a2, 1);
      MmPC mff{(std::uint32_t)ffn, (std::uint32_t)d};
      rec.op(pMatmul, {bg, bGate[l], bxn}, &mff, (std::uint32_t)ffn);
      rec.op(pMatmul, {bu, bUp[l], bxn}, &mff, (std::uint32_t)ffn);
      NPC nf{(std::uint32_t)ffn};
      rec.op(pSwiglu, {bact, bg, bu}, &nf, g256(ffn));
      MmPC mdn{(std::uint32_t)d, (std::uint32_t)ffn};
      rec.op(pMatmul, {btmp, bDown[l], bact}, &mdn, (std::uint32_t)d);
      rec.op(pAdd, {bx, btmp}, &nd, g256(d));
    }
    struct RmsPC2 { std::uint32_t n; float eps; } af{(std::uint32_t)d, eps};
    rec.op(pRms, {bxn, bx, bOutNorm}, &af, 1);
    struct MmPC2 { std::uint32_t rows, cols; } mlg{(std::uint32_t)vocab, (std::uint32_t)d};
    rec.op(pMatmul, {blogits, bOutput, bxn}, &mlg, (std::uint32_t)vocab);
    vkEndCommandBuffer(cmd);
    if (!rec.ok) {
      ran = false;
      break;
    }

    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    if (vkQueueSubmit(c.queue, 1, &si, fence) != VK_SUCCESS ||
        vkWaitForFences(c.device, 1, &fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) {
      ran = false;
      break;
    }
    vkResetFences(c.device, 1, &fence);

    std::vector<float> got(vocab), ref;
    for (auto& b : owned)
      if (b.buf == blogits) download(b, got.data(), vocab * sizeof(float));
    cpuForward(tokens[pos], pos, ref);
    for (int i = 0; i < vocab; ++i) maxErr = std::max(maxErr, std::fabs(got[i] - ref[i]));
  }

  // cleanup
  if (descPool) vkDestroyDescriptorPool(c.device, descPool, nullptr);
  if (fence) vkDestroyFence(c.device, fence, nullptr);
  if (cmd) vkFreeCommandBuffers(c.device, c.pool, 1, &cmd);
  for (auto& b : owned) b.destroy();
  for (Pipe* p : {&pEmbed, &pMatmul, &pRms, &pRope, &pKv, &pAttn, &pSwiglu, &pAdd}) destroyPipe(c, *p);

  if (!infraOk) return {true, false, "forward setup failed (pipelines/buffers)"};
  if (!ran) return {true, false, "forward dispatch failed"};
  const bool ok = maxErr < 2e-2f;
  return {true, ok,
          (ok ? "Vulkan forward pass (2-layer, 3 positions) matches CPU reference (max err "
              : "Vulkan forward disagrees with CPU (max err ") +
              std::to_string(maxErr) + ") on " + dp.deviceName};
}

SelfTestResult multiSessionSelfTest() {
  // Tiny synthetic F32 model built through the real createVulkanModel path with 2 KV sessions.
  VulkanModelConfig cfg;
  cfg.nLayers = 2;
  cfg.dModel = 32;
  cfg.nHeads = 4;
  cfg.headDim = 8;
  cfg.nKv = 2;
  cfg.ffn = 64;
  cfg.vocab = 16;
  cfg.maxSeq = 8;
  cfg.normEps = 1e-5f;
  cfg.ropeFreqBase = 10000.0f;
  const int d = cfg.dModel, kvDim = cfg.nKv * cfg.headDim, ffn = cfg.ffn, vocab = cfg.vocab,
            qDim = cfg.nHeads * cfg.headDim;
  auto gen = [](int seed, int i) { return 0.01f * (((i * 7 + seed * 13) % 17) - 8); };

  std::vector<float> tokEmbd(static_cast<std::size_t>(vocab) * d), outNorm(d, 1.0f),
      outputW(static_cast<std::size_t>(vocab) * d);
  for (int i = 0; i < vocab * d; ++i) {
    tokEmbd[i] = gen(1, i);
    outputW[i] = gen(2, i);
  }
  for (int i = 0; i < d; ++i) outNorm[i] = 1.0f + 0.01f * i;
  struct LW {
    std::vector<float> attnNorm, ffnNorm, wq, wk, wv, wo, gate, up, down;
  };
  std::vector<LW> lw(cfg.nLayers);
  for (int l = 0; l < cfg.nLayers; ++l) {
    LW& w = lw[l];
    w.attnNorm.assign(d, 0.0f);
    w.ffnNorm.assign(d, 0.0f);
    for (int i = 0; i < d; ++i) {
      w.attnNorm[i] = 1.0f + 0.01f * ((i + l) % 5);
      w.ffnNorm[i] = 1.0f + 0.01f * ((i + l) % 3);
    }
    w.wq.resize(static_cast<std::size_t>(qDim) * d);
    w.wo.resize(static_cast<std::size_t>(d) * qDim);
    w.wk.resize(static_cast<std::size_t>(kvDim) * d);
    w.wv.resize(static_cast<std::size_t>(kvDim) * d);
    w.gate.resize(static_cast<std::size_t>(ffn) * d);
    w.up.resize(static_cast<std::size_t>(ffn) * d);
    w.down.resize(static_cast<std::size_t>(d) * ffn);
    for (std::size_t i = 0; i < w.wq.size(); ++i) w.wq[i] = gen(10 + l, static_cast<int>(i));
    for (std::size_t i = 0; i < w.wo.size(); ++i) w.wo[i] = gen(20 + l, static_cast<int>(i));
    for (std::size_t i = 0; i < w.wk.size(); ++i) w.wk[i] = gen(30 + l, static_cast<int>(i));
    for (std::size_t i = 0; i < w.wv.size(); ++i) w.wv[i] = gen(40 + l, static_cast<int>(i));
    for (std::size_t i = 0; i < w.gate.size(); ++i) w.gate[i] = gen(50 + l, static_cast<int>(i));
    for (std::size_t i = 0; i < w.up.size(); ++i) w.up[i] = gen(60 + l, static_cast<int>(i));
    for (std::size_t i = 0; i < w.down.size(); ++i) w.down[i] = gen(70 + l, static_cast<int>(i));
  }
  auto f32 = [](const std::vector<float>& v, int rows, int cols) {
    return VulkanWeight{v.data(), 0u, rows, cols};
  };
  std::vector<VulkanLayer> layers(cfg.nLayers);
  for (int l = 0; l < cfg.nLayers; ++l)
    layers[l] = {lw[l].attnNorm.data(), lw[l].ffnNorm.data(), f32(lw[l].wq, qDim, d),
                 f32(lw[l].wk, kvDim, d), f32(lw[l].wv, kvDim, d), f32(lw[l].wo, d, qDim),
                 f32(lw[l].gate, ffn, d), f32(lw[l].up, ffn, d), f32(lw[l].down, d, ffn)};

  std::string err;
  auto model = createVulkanModel(cfg, tokEmbd.data(), outNorm.data(), f32(outputW, vocab, d), layers,
                                 err, /*maxSessions=*/2);
  if (!model) return {true, false, "multi-session: createVulkanModel failed: " + err};

  const int A[3] = {1, 5, 9}, B[3] = {2, 6, 10};
  auto runAlone = [&](const int* seq) {
    const int s = model->openSession();
    std::vector<float> out;
    for (int p = 0; p < 3; ++p) out = model->forward(s, seq[p], p);  // auto-copies (returns by ref)
    model->closeSession(s);
    return out;
  };
  const std::vector<float> refA = runAlone(A), refB = runAlone(B);

  const int s0 = model->openSession(), s1 = model->openSession();
  if (s0 == kNoVkSession || s1 == kNoVkSession || s0 == s1)
    return {true, false, "multi-session: openSession did not yield two distinct slots"};
  std::vector<float> gotA, gotB;
  for (int p = 0; p < 3; ++p) {
    const std::vector<float> la = model->forward(s0, A[p], p);
    if (p == 2) gotA = la;
    const std::vector<float> lb = model->forward(s1, B[p], p);
    if (p == 2) gotB = lb;
  }
  model->closeSession(s0);
  model->closeSession(s1);

  float e = 0.0f;
  for (int i = 0; i < vocab; ++i) {
    e = std::max(e, std::fabs(gotA[i] - refA[i]));
    e = std::max(e, std::fabs(gotB[i] - refB[i]));
  }
  if (e > 1e-3f)
    return {true, false,
            "multi-session isolation FAILED (interleaved != sequential, max err " +
                std::to_string(e) + ")"};
  return {true, true,
          "2 sessions isolated: interleaved output matches sequential (max err " +
              std::to_string(e) + ")"};
}

// ---- GPU-resident model runner (Milestone 4b) ----------------------------------------------
namespace {

// Byte size of a [rows,cols] weight in its GGUF quant type (F32=0, Q8_0=8, Q4_K=12, Q6_K=14).
VkDeviceSize weightBytes(std::uint32_t type, int rows, int cols) {
  const std::size_t n = static_cast<std::size_t>(rows) * cols;
  switch (type) {
    case 0: return n * sizeof(float);       // F32
    case 8: return n / 32 * 34;             // Q8_0
    case 12: return n / 256 * 144;          // Q4_K
    case 14: return n / 256 * 210;          // Q6_K
    default: return 0;
  }
}

struct DevW {
  VkBuffer buf = VK_NULL_HANDLE;
  std::uint32_t type = 0;
  int rows = 0;
  int cols = 0;
};

class VulkanModelImpl final : public VulkanModel {
 public:
  VulkanModelImpl(Context&& c, const VulkanModelConfig& cfg, int maxSessions)
      : c_(std::move(c)), cfg_(cfg), maxSessions_(maxSessions < 1 ? 1 : maxSessions) {}

  ~VulkanModelImpl() override {
    if (descPool_) vkDestroyDescriptorPool(c_.device, descPool_, nullptr);
    if (fence_) vkDestroyFence(c_.device, fence_, nullptr);
    if (cmd_) vkFreeCommandBuffers(c_.device, c_.pool, 1, &cmd_);
    for (Pipe* p : {&pEmbed_, &pMatmulF32_, &pQ8_, &pQ4_, &pQ6_, &pRms_, &pRope_, &pKv_, &pAttn_,
                    &pSwiglu_, &pAdd_})
      destroyPipe(c_, *p);
    for (auto& b : owned_) b.destroy();
    for (auto& b : kc_) b.destroy();
    for (auto& b : vc_) b.destroy();
  }

  bool init(const float* tokEmbdF32, const float* outputNorm, const VulkanWeight& output,
            const std::vector<VulkanLayer>& layers, std::string& err) {
    const int d = cfg_.dModel, kvDim = cfg_.nKv * cfg_.headDim, ffn = cfg_.ffn, vocab = cfg_.vocab,
              L = cfg_.nLayers, qDim = cfg_.nHeads * cfg_.headDim;

    if (!makePipe(c_, embed_row_spv, sizeof(embed_row_spv), 2, 8, pEmbed_) ||
        !makePipe(c_, matmul_f32_spv, sizeof(matmul_f32_spv), 3, 8, pMatmulF32_) ||
        !makePipe(c_, qmatmul_q8_0_spv, sizeof(qmatmul_q8_0_spv), 3, 8, pQ8_) ||
        !makePipe(c_, qmatmul_q4_k_spv, sizeof(qmatmul_q4_k_spv), 3, 8, pQ4_) ||
        !makePipe(c_, qmatmul_q6_k_spv, sizeof(qmatmul_q6_k_spv), 3, 8, pQ6_) ||
        !makePipe(c_, rmsnorm_spv, sizeof(rmsnorm_spv), 3, 8, pRms_) ||
        !makePipe(c_, rope_spv, sizeof(rope_spv), 1, 16, pRope_) ||
        !makePipe(c_, kv_store_spv, sizeof(kv_store_spv), 2, 16, pKv_) ||
        !makePipe(c_, attention_spv, sizeof(attention_spv), 4, 28, pAttn_) ||
        !makePipe(c_, swiglu_spv, sizeof(swiglu_spv), 3, 4, pSwiglu_) ||
        !makePipe(c_, add_spv, sizeof(add_spv), 2, 4, pAdd_)) {
      err = "failed to build compute pipelines";
      return false;
    }

    bool ok = true;
    // Everything here lives in DEVICE_LOCAL memory (real VRAM on a discrete GPU) and is filled once
    // through a staging copy. The weights dominate: on a discrete card the previous host-visible
    // allocation meant every GEMV pulled the whole weight set across PCIe once per token.
    auto mkBytes = [&](VkDeviceSize bytes, const void* src, VkDeviceSize srcBytes) -> VkBuffer {
      Buffer b{};
      if (bytes == 0 || !makeDeviceBuffer(c_, (bytes + 3) & ~VkDeviceSize(3), b)) {
        ok = false;
        return VK_NULL_HANDLE;
      }
      if (src && !uploadDevice(c_, b, src, srcBytes)) {
        b.destroy();
        ok = false;
        return VK_NULL_HANDLE;
      }
      owned_.push_back(b);
      return owned_.back().buf;
    };
    auto mkF = [&](const float* p, std::size_t n) {
      return mkBytes(n * sizeof(float), p, n * sizeof(float));
    };
    auto mkW = [&](const VulkanWeight& w) -> DevW {
      const VkDeviceSize bytes = weightBytes(w.ggmlType, w.rows, w.cols);
      VkBuffer b = mkBytes(bytes, w.host, bytes);
      return {b, w.ggmlType, w.rows, w.cols};
    };

    bTok_ = mkF(tokEmbdF32, static_cast<std::size_t>(vocab) * d);
    bOutNorm_ = mkF(outputNorm, d);
    output_ = mkW(output);
    layers_.resize(L);
    for (int l = 0; l < L; ++l) {
      layers_[l].attnNorm = mkF(layers[l].attnNorm, d);
      layers_[l].ffnNorm = mkF(layers[l].ffnNorm, d);
      layers_[l].wq = mkW(layers[l].wq);
      layers_[l].wk = mkW(layers[l].wk);
      layers_[l].wv = mkW(layers[l].wv);
      layers_[l].wo = mkW(layers[l].wo);
      layers_[l].gate = mkW(layers[l].ffnGate);
      layers_[l].up = mkW(layers[l].ffnUp);
      layers_[l].down = mkW(layers[l].ffnDown);
    }
    // scratch
    bx_ = mkBytes(d * sizeof(float), nullptr, 0);
    bxn_ = mkBytes(d * sizeof(float), nullptr, 0);
    bq_ = mkBytes(qDim * sizeof(float), nullptr, 0);
    bk_ = mkBytes(kvDim * sizeof(float), nullptr, 0);
    bv_ = mkBytes(kvDim * sizeof(float), nullptr, 0);
    battn_ = mkBytes(qDim * sizeof(float), nullptr, 0);
    btmp_ = mkBytes(d * sizeof(float), nullptr, 0);
    bg_ = mkBytes(ffn * sizeof(float), nullptr, 0);
    bu_ = mkBytes(ffn * sizeof(float), nullptr, 0);
    bact_ = mkBytes(ffn * sizeof(float), nullptr, 0);
    // The one exception to device-local: the host maps and reads this every token, so it has to stay
    // host-visible. It is ~128 KB per token against ~500 MB of weight traffic — irrelevant either way.
    {
      Buffer b{};
      if (!makeBuffer(c_, vocab * sizeof(float), b)) {
        ok = false;
      } else {
        owned_.push_back(b);
        blogits_ = owned_.back().buf;
      }
    }
    // Per-session KV cache: each session owns an independent K and V buffer (isolation without any
    // shader change — the kv_store/attention indexing stays (layer*maxSeq + pos)*kvDim within the
    // session's own buffer). reset/openSession zero a single session's pair.
    const VkDeviceSize kvBytes =
        static_cast<VkDeviceSize>(L) * cfg_.maxSeq * kvDim * sizeof(float);
    kc_.resize(maxSessions_);
    vc_.resize(maxSessions_);
    sessionUsed_.assign(maxSessions_, 0);
    for (int s = 0; s < maxSessions_ && ok; ++s)
      if (!makeBuffer(c_, kvBytes, kc_[s]) || !makeBuffer(c_, kvBytes, vc_[s])) ok = false;
    if (ok)
      for (int s = 0; s < maxSessions_; ++s) {
        kc_[s].zero();
        vc_[s].zero();
      }
    if (!ok) {
      err = "failed to allocate device buffers";
      return false;
    }

    VkCommandBufferAllocateInfo cbai{};
    cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    cbai.commandPool = c_.pool;
    cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cbai.commandBufferCount = 1;
    VkFenceCreateInfo fci{};
    fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    const std::uint32_t sets = static_cast<std::uint32_t>((L + 1) * 18 + 8);
    VkDescriptorPoolSize dps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, sets * 4};
    VkDescriptorPoolCreateInfo dpci{};
    dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = sets;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &dps;
    if (vkAllocateCommandBuffers(c_.device, &cbai, &cmd_) != VK_SUCCESS ||
        vkCreateFence(c_.device, &fci, nullptr, &fence_) != VK_SUCCESS ||
        vkCreateDescriptorPool(c_.device, &dpci, nullptr, &descPool_) != VK_SUCCESS) {
      err = "failed to allocate command/descriptor infrastructure";
      return false;
    }
    logits_.resize(vocab);
    ready_ = true;
    return true;
  }

  int openSession() override {
    for (int s = 0; s < maxSessions_; ++s)
      if (!sessionUsed_[s]) {
        sessionUsed_[s] = 1;
        kc_[s].zero();
        vc_[s].zero();
        return s;
      }
    return kNoVkSession;
  }
  void closeSession(int session) override {
    if (session >= 0 && session < maxSessions_) sessionUsed_[session] = 0;
  }
  void resetSession(int session) override {
    if (session >= 0 && session < maxSessions_) {
      kc_[session].zero();
      vc_[session].zero();
    }
  }
  const std::vector<float>& forward(int token, int pos) override { return forward(0, token, pos); }
  void reset() override { resetSession(0); }

  const std::vector<float>& forward(int session, int token, int pos) override {
    if (!ready_ || session < 0 || session >= maxSessions_) return logits_;
    VkBuffer kcBuf = kc_[session].buf, vcBuf = vc_[session].buf;
    const int d = cfg_.dModel, kvDim = cfg_.nKv * cfg_.headDim, ffn = cfg_.ffn, vocab = cfg_.vocab,
              L = cfg_.nLayers, nHeads = cfg_.nHeads, headDim = cfg_.headDim, nKv = cfg_.nKv,
              maxSeq = cfg_.maxSeq;
    const float eps = cfg_.normEps, freqBase = cfg_.ropeFreqBase;
    auto g256 = [](int n) { return static_cast<std::uint32_t>((n + 255) / 256); };

    vkResetDescriptorPool(c_.device, descPool_, 0);
    vkResetCommandBuffer(cmd_, 0);
    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd_, &bi);
    Recorder rec{c_, cmd_, descPool_};

    // matmul dispatched by quant type: F32 uses matmul_f32 (bindings out,W,x; one workgroup/row);
    // quant uses qmatmul_* (bindings W,x,out; one invocation/row).
    auto matmul = [&](VkBuffer out, const DevW& w, VkBuffer in) {
      struct {
        std::uint32_t rows, cols;
      } pc{static_cast<std::uint32_t>(w.rows), static_cast<std::uint32_t>(w.cols)};
      if (w.type == 0) {
        rec.op(pMatmulF32_, {out, w.buf, in}, &pc, static_cast<std::uint32_t>(w.rows));
      } else {
        const Pipe& p = (w.type == 8) ? pQ8_ : (w.type == 12) ? pQ4_ : pQ6_;
        rec.op(p, {w.buf, in, out}, &pc, static_cast<std::uint32_t>(w.rows));  // one workgroup/row
      }
    };

    struct {
      std::uint32_t token, d;
    } ePC{static_cast<std::uint32_t>(token), static_cast<std::uint32_t>(d)};
    rec.op(pEmbed_, {bx_, bTok_}, &ePC, g256(d));

    for (int l = 0; l < L; ++l) {
      auto& lw = layers_[l];
      struct RmsPC {
        std::uint32_t n;
        float eps;
      } rmsAttn{static_cast<std::uint32_t>(d), eps};
      rec.op(pRms_, {bxn_, bx_, lw.attnNorm}, &rmsAttn, 1);
      matmul(bq_, lw.wq, bxn_);
      matmul(bk_, lw.wk, bxn_);
      matmul(bv_, lw.wv, bxn_);
      struct RopePC {
        std::uint32_t nh, hd;
        std::int32_t pos;
        float base;
      } rq{static_cast<std::uint32_t>(nHeads), static_cast<std::uint32_t>(headDim), pos, freqBase},
          rk{static_cast<std::uint32_t>(nKv), static_cast<std::uint32_t>(headDim), pos, freqBase};
      // rope.comp has local_size_x=64, so it needs ceil(pairs/64) workgroups (NOT g256 — that would
      // under-launch and leave most q/k pairs un-rotated once nHeads*headDim/2 > 64).
      rec.op(pRope_, {bq_}, &rq, static_cast<std::uint32_t>((nHeads * headDim / 2 + 63) / 64));
      rec.op(pRope_, {bk_}, &rk, static_cast<std::uint32_t>((nKv * headDim / 2 + 63) / 64));
      struct KvPC {
        std::uint32_t layer, pos, maxSeq, kvDim;
      } kv{static_cast<std::uint32_t>(l), static_cast<std::uint32_t>(pos),
           static_cast<std::uint32_t>(maxSeq), static_cast<std::uint32_t>(kvDim)};
      rec.op(pKv_, {kcBuf, bk_}, &kv, g256(kvDim));
      rec.op(pKv_, {vcBuf, bv_}, &kv, g256(kvDim));
      struct AttnPC {
        std::uint32_t nHeads, nKv, headDim, seqLen, kvDim, layer, maxSeq;
      } ap{static_cast<std::uint32_t>(nHeads), static_cast<std::uint32_t>(nKv),
           static_cast<std::uint32_t>(headDim), static_cast<std::uint32_t>(pos + 1),
           static_cast<std::uint32_t>(kvDim), static_cast<std::uint32_t>(l),
           static_cast<std::uint32_t>(maxSeq)};
      rec.op(pAttn_, {battn_, bq_, kcBuf, vcBuf}, &ap, static_cast<std::uint32_t>(nHeads));
      matmul(btmp_, lw.wo, battn_);
      struct NPC {
        std::uint32_t n;
      } nd{static_cast<std::uint32_t>(d)};
      rec.op(pAdd_, {bx_, btmp_}, &nd, g256(d));
      struct RmsPC rmsFfn{static_cast<std::uint32_t>(d), eps};
      rec.op(pRms_, {bxn_, bx_, lw.ffnNorm}, &rmsFfn, 1);
      matmul(bg_, lw.gate, bxn_);
      matmul(bu_, lw.up, bxn_);
      struct NPC nf{static_cast<std::uint32_t>(ffn)};
      rec.op(pSwiglu_, {bact_, bg_, bu_}, &nf, g256(ffn));
      matmul(btmp_, lw.down, bact_);
      rec.op(pAdd_, {bx_, btmp_}, &nd, g256(d));
    }
    struct {
      std::uint32_t n;
      float eps;
    } rmsOut{static_cast<std::uint32_t>(d), eps};
    rec.op(pRms_, {bxn_, bx_, bOutNorm_}, &rmsOut, 1);
    matmul(blogits_, output_, bxn_);
    vkEndCommandBuffer(cmd_);

    if (rec.ok) {
      VkSubmitInfo si{};
      si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
      si.commandBufferCount = 1;
      si.pCommandBuffers = &cmd_;
      if (vkQueueSubmit(c_.queue, 1, &si, fence_) == VK_SUCCESS) {
        vkWaitForFences(c_.device, 1, &fence_, VK_TRUE, UINT64_MAX);
        vkResetFences(c_.device, 1, &fence_);
        for (auto& b : owned_)
          if (b.buf == blogits_) download(b, logits_.data(), vocab * sizeof(float));
      }
    }
    return logits_;
  }

 private:
  Context c_;
  VulkanModelConfig cfg_;
  int maxSessions_ = 1;
  Pipe pEmbed_, pMatmulF32_, pQ8_, pQ4_, pQ6_, pRms_, pRope_, pKv_, pAttn_, pSwiglu_, pAdd_;
  std::vector<Buffer> owned_;
  std::vector<Buffer> kc_, vc_;      // one K/V buffer per session
  std::vector<char> sessionUsed_;    // slot occupancy (char, not vector<bool>)
  VkBuffer bTok_ = VK_NULL_HANDLE, bOutNorm_ = VK_NULL_HANDLE, bx_ = VK_NULL_HANDLE,
           bxn_ = VK_NULL_HANDLE, bq_ = VK_NULL_HANDLE, bk_ = VK_NULL_HANDLE, bv_ = VK_NULL_HANDLE,
           battn_ = VK_NULL_HANDLE, btmp_ = VK_NULL_HANDLE, bg_ = VK_NULL_HANDLE,
           bu_ = VK_NULL_HANDLE, bact_ = VK_NULL_HANDLE, blogits_ = VK_NULL_HANDLE;
  DevW output_;
  struct LayerW {
    VkBuffer attnNorm, ffnNorm;
    DevW wq, wk, wv, wo, gate, up, down;
  };
  std::vector<LayerW> layers_;
  VkCommandBuffer cmd_ = VK_NULL_HANDLE;
  VkFence fence_ = VK_NULL_HANDLE;
  VkDescriptorPool descPool_ = VK_NULL_HANDLE;
  std::vector<float> logits_;
  bool ready_ = false;
};

}  // namespace

std::unique_ptr<VulkanModel> createVulkanModel(const VulkanModelConfig& cfg, const float* tokenEmbdF32,
                                               const float* outputNorm, const VulkanWeight& output,
                                               const std::vector<VulkanLayer>& layers,
                                               std::string& error, int maxSessions) {
  Context c = makeContext();
  if (!c.ok) {
    error = "no Vulkan device present";
    return nullptr;
  }
  auto m = std::make_unique<VulkanModelImpl>(std::move(c), cfg, maxSessions);
  if (!m->init(tokenEmbdF32, outputNorm, output, layers, error)) return nullptr;
  return m;
}

}  // namespace qorvix::vulkan
