// Real Vulkan compute backend. Compiled only when QORVIX_ENABLE_VULKAN is ON and the Vulkan loader
// + a GLSL->SPIR-V compiler were found (see vulkan/CMakeLists.txt). Provides the same facade as the
// CUDA backend so the CLI/tests drive either without #ifdefs.
//
// Design: correctness-first, headless-verifiable. All buffers are HOST_VISIBLE|HOST_COHERENT so a
// dispatch is upload -> record -> submit -> wait -> read with no staging; this runs identically on
// Mesa's software device (lavapipe) — where the argmax-parity gate is checked with no physical GPU
// — and on real NVIDIA/AMD/Apple/Intel hardware (device-local + staging is a later throughput
// milestone, not a correctness one). The compute shaders are SPIR-V embedded at build time.
#include "qorvix/vulkan/backend.hpp"

#include <vulkan/vulkan.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <functional>
#include <string>
#include <vector>

#include "qmatmul_q8_0_spv.h"  // const uint32_t qmatmul_q8_0_spv[] — generated by glslang
#include "qmatmul_q4_k_spv.h"  // const uint32_t qmatmul_q4_k_spv[]
#include "qmatmul_q6_k_spv.h"  // const uint32_t qmatmul_q6_k_spv[]
#include "rmsnorm_spv.h"       // const uint32_t rmsnorm_spv[]
#include "rope_spv.h"          // const uint32_t rope_spv[]
#include "swiglu_spv.h"        // const uint32_t swiglu_spv[]
#include "add_spv.h"           // const uint32_t add_spv[]
#include "attention_spv.h"     // const uint32_t attention_spv[]

namespace qorvix::vulkan {
namespace {

// fp16 (IEEE half) <-> float, matching the GGUF scale encoding the shader decodes with
// unpackHalf2x16. Kept on the host so the reference and the shader agree bit-for-bit on the scale.
float decodeHalf(std::uint16_t h) {
  const std::uint32_t sign = (h & 0x8000u) << 16;
  const std::uint32_t exp = (h >> 10) & 0x1F;
  const std::uint32_t mant = h & 0x3FF;
  std::uint32_t bits;
  if (exp == 0) {
    if (mant == 0) {
      bits = sign;  // +/- zero
    } else {
      // subnormal half -> normalized float
      int e = -1;
      std::uint32_t m = mant;
      do {
        m <<= 1;
        ++e;
      } while ((m & 0x400u) == 0);
      m &= 0x3FFu;
      bits = sign | ((127 - 15 - e) << 23) | (m << 13);
    }
  } else if (exp == 0x1F) {
    bits = sign | 0x7F800000u | (mant << 13);  // inf/nan
  } else {
    bits = sign | ((exp - 15 + 127) << 23) | (mant << 13);
  }
  float f;
  std::memcpy(&f, &bits, 4);
  return f;
}

std::uint16_t encodeHalf(float f) {
  std::uint32_t x;
  std::memcpy(&x, &f, 4);
  const std::uint32_t sign = (x >> 16) & 0x8000u;
  std::int32_t exp = static_cast<std::int32_t>((x >> 23) & 0xFF) - 127 + 15;
  std::uint32_t mant = x & 0x7FFFFFu;
  if (exp <= 0) return static_cast<std::uint16_t>(sign);          // flush tiny to zero (sufficient here)
  if (exp >= 0x1F) return static_cast<std::uint16_t>(sign | 0x7C00u);  // overflow -> inf
  return static_cast<std::uint16_t>(sign | (exp << 10) | (mant >> 13));
}

// 6-bit (scale, min) unpack for sub-block j of a Q4_K scales array — the host mirror of the
// shader's getScaleMinK4 (verbatim from ggml), so the reference and the shader agree.
void getScaleMinK4(int j, const std::uint8_t* q, unsigned char& d, unsigned char& m) {
  if (j < 4) {
    d = q[j] & 63;
    m = q[j + 4] & 63;
  } else {
    d = (q[j + 4] & 0xF) | ((q[j - 4] >> 6) << 4);
    m = (q[j + 4] >> 4) | ((q[j] >> 6) << 4);
  }
}

// ---- minimal Vulkan compute context ---------------------------------------------------------
struct Context {
  VkInstance instance = VK_NULL_HANDLE;
  VkPhysicalDevice phys = VK_NULL_HANDLE;
  VkDevice device = VK_NULL_HANDLE;
  VkQueue queue = VK_NULL_HANDLE;
  std::uint32_t queueFamily = 0;
  VkCommandPool pool = VK_NULL_HANDLE;
  VkPhysicalDeviceMemoryProperties memProps{};
  bool ok = false;

  ~Context() {
    if (device) {
      if (pool) vkDestroyCommandPool(device, pool, nullptr);
      vkDestroyDevice(device, nullptr);
    }
    if (instance) vkDestroyInstance(instance, nullptr);
  }
};

// Pick a queue family that supports compute.
bool findComputeQueue(VkPhysicalDevice phys, std::uint32_t& family) {
  std::uint32_t n = 0;
  vkGetPhysicalDeviceQueueFamilyProperties(phys, &n, nullptr);
  std::vector<VkQueueFamilyProperties> qf(n);
  vkGetPhysicalDeviceQueueFamilyProperties(phys, &n, qf.data());
  for (std::uint32_t i = 0; i < n; ++i) {
    if (qf[i].queueFlags & VK_QUEUE_COMPUTE_BIT) {
      family = i;
      return true;
    }
  }
  return false;
}

// Prefer a discrete GPU, then integrated, then anything (incl. the CPU software device).
VkPhysicalDevice pickPhysical(VkInstance inst) {
  std::uint32_t n = 0;
  vkEnumeratePhysicalDevices(inst, &n, nullptr);
  if (n == 0) return VK_NULL_HANDLE;
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(inst, &n, devs.data());
  VkPhysicalDevice best = VK_NULL_HANDLE;
  int bestRank = -1;
  for (auto d : devs) {
    VkPhysicalDeviceProperties p{};
    vkGetPhysicalDeviceProperties(d, &p);
    int rank = 0;
    switch (p.deviceType) {
      case VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU: rank = 4; break;
      case VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU: rank = 3; break;
      case VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU: rank = 2; break;
      case VK_PHYSICAL_DEVICE_TYPE_CPU: rank = 1; break;
      default: rank = 0; break;
    }
    std::uint32_t fam = 0;
    if (rank > bestRank && findComputeQueue(d, fam)) {
      best = d;
      bestRank = rank;
    }
  }
  return best;
}

Context makeContext() {
  Context c;
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.pApplicationName = "qorvix";
  app.apiVersion = VK_API_VERSION_1_1;

  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  if (vkCreateInstance(&ici, nullptr, &c.instance) != VK_SUCCESS) return c;

  c.phys = pickPhysical(c.instance);
  if (!c.phys) return c;
  if (!findComputeQueue(c.phys, c.queueFamily)) return c;
  vkGetPhysicalDeviceMemoryProperties(c.phys, &c.memProps);

  const float prio = 1.0f;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = c.queueFamily;
  qci.queueCount = 1;
  qci.pQueuePriorities = &prio;

  VkDeviceCreateInfo dci{};
  dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  dci.queueCreateInfoCount = 1;
  dci.pQueueCreateInfos = &qci;
  if (vkCreateDevice(c.phys, &dci, nullptr, &c.device) != VK_SUCCESS) return c;
  vkGetDeviceQueue(c.device, c.queueFamily, 0, &c.queue);

  VkCommandPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  pci.queueFamilyIndex = c.queueFamily;
  if (vkCreateCommandPool(c.device, &pci, nullptr, &c.pool) != VK_SUCCESS) return c;

  c.ok = true;
  return c;
}

std::uint32_t findMemType(const Context& c, std::uint32_t typeBits, VkMemoryPropertyFlags want) {
  for (std::uint32_t i = 0; i < c.memProps.memoryTypeCount; ++i) {
    if ((typeBits & (1u << i)) && (c.memProps.memoryTypes[i].propertyFlags & want) == want) return i;
  }
  return UINT32_MAX;
}

// A host-visible, coherent storage buffer. Correctness-first: no staging, map/unmap directly.
struct Buffer {
  VkDevice device = VK_NULL_HANDLE;
  VkBuffer buf = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  VkDeviceSize size = 0;

  void destroy() {
    if (buf) vkDestroyBuffer(device, buf, nullptr);
    if (mem) vkFreeMemory(device, mem, nullptr);
    buf = VK_NULL_HANDLE;
    mem = VK_NULL_HANDLE;
  }
};

bool makeBuffer(const Context& c, VkDeviceSize size, Buffer& out) {
  out.device = c.device;
  out.size = size;
  VkBufferCreateInfo bci{};
  bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bci.size = size;
  bci.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(c.device, &bci, nullptr, &out.buf) != VK_SUCCESS) return false;

  VkMemoryRequirements req{};
  vkGetBufferMemoryRequirements(c.device, out.buf, &req);
  const std::uint32_t mt = findMemType(
      c, req.memoryTypeBits, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  if (mt == UINT32_MAX) return false;

  VkMemoryAllocateInfo mai{};
  mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  mai.allocationSize = req.size;
  mai.memoryTypeIndex = mt;
  if (vkAllocateMemory(c.device, &mai, nullptr, &out.mem) != VK_SUCCESS) return false;
  return vkBindBufferMemory(c.device, out.buf, out.mem, 0) == VK_SUCCESS;
}

bool upload(const Buffer& b, const void* src, VkDeviceSize n) {
  void* p = nullptr;
  if (vkMapMemory(b.device, b.mem, 0, n, 0, &p) != VK_SUCCESS) return false;
  std::memcpy(p, src, n);
  vkUnmapMemory(b.device, b.mem);
  return true;
}

bool download(const Buffer& b, void* dst, VkDeviceSize n) {
  void* p = nullptr;
  if (vkMapMemory(b.device, b.mem, 0, n, 0, &p) != VK_SUCCESS) return false;
  std::memcpy(dst, p, n);
  vkUnmapMemory(b.device, b.mem);
  return true;
}

// One-shot compute pipeline over N storage-buffer bindings with a push-constant block. Builds the
// pipeline, dispatches `groups` workgroups, and waits. Returns false on any Vulkan error.
bool dispatch(const Context& c, const std::uint32_t* spirv, std::size_t spirvBytes,
              const std::vector<VkBuffer>& buffers, const void* push, std::uint32_t pushSize,
              std::uint32_t groups) {
  const std::uint32_t nb = static_cast<std::uint32_t>(buffers.size());

  std::vector<VkDescriptorSetLayoutBinding> binds(nb);
  for (std::uint32_t i = 0; i < nb; ++i) {
    binds[i] = {i, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};
  }
  VkDescriptorSetLayoutCreateInfo dslci{};
  dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  dslci.bindingCount = nb;
  dslci.pBindings = binds.data();
  VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
  if (vkCreateDescriptorSetLayout(c.device, &dslci, nullptr, &dsl) != VK_SUCCESS) return false;

  VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize};
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.setLayoutCount = 1;
  plci.pSetLayouts = &dsl;
  plci.pushConstantRangeCount = pushSize ? 1 : 0;
  plci.pPushConstantRanges = pushSize ? &pcr : nullptr;
  VkPipelineLayout layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(c.device, &plci, nullptr, &layout) != VK_SUCCESS) {
    vkDestroyDescriptorSetLayout(c.device, dsl, nullptr);
    return false;
  }

  VkShaderModuleCreateInfo smci{};
  smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  smci.codeSize = spirvBytes;
  smci.pCode = spirv;
  VkShaderModule shader = VK_NULL_HANDLE;
  bool okAll = false;
  VkPipeline pipe = VK_NULL_HANDLE;
  VkDescriptorPool descPool = VK_NULL_HANDLE;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  VkFence fence = VK_NULL_HANDLE;
  do {
    if (vkCreateShaderModule(c.device, &smci, nullptr, &shader) != VK_SUCCESS) break;

    VkPipelineShaderStageCreateInfo stage{};
    stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    stage.module = shader;
    stage.pName = "main";
    VkComputePipelineCreateInfo cpci{};
    cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage = stage;
    cpci.layout = layout;
    if (vkCreateComputePipelines(c.device, VK_NULL_HANDLE, 1, &cpci, nullptr, &pipe) != VK_SUCCESS)
      break;

    VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nb};
    VkDescriptorPoolCreateInfo dpci{};
    dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = 1;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(c.device, &dpci, nullptr, &descPool) != VK_SUCCESS) break;

    VkDescriptorSetAllocateInfo dsai{};
    dsai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    dsai.descriptorPool = descPool;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dsl;
    VkDescriptorSet set = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(c.device, &dsai, &set) != VK_SUCCESS) break;

    std::vector<VkDescriptorBufferInfo> dbi(nb);
    std::vector<VkWriteDescriptorSet> writes(nb);
    for (std::uint32_t i = 0; i < nb; ++i) {
      dbi[i] = {buffers[i], 0, VK_WHOLE_SIZE};
      writes[i] = {};
      writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
      writes[i].dstSet = set;
      writes[i].dstBinding = i;
      writes[i].descriptorCount = 1;
      writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
      writes[i].pBufferInfo = &dbi[i];
    }
    vkUpdateDescriptorSets(c.device, nb, writes.data(), 0, nullptr);

    VkCommandBufferAllocateInfo cbai{};
    cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    cbai.commandPool = c.pool;
    cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cbai.commandBufferCount = 1;
    if (vkAllocateCommandBuffers(c.device, &cbai, &cmd) != VK_SUCCESS) break;

    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipe);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layout, 0, 1, &set, 0, nullptr);
    if (pushSize) vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize, push);
    vkCmdDispatch(cmd, groups, 1, 1);
    vkEndCommandBuffer(cmd);

    VkFenceCreateInfo fci{};
    fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    if (vkCreateFence(c.device, &fci, nullptr, &fence) != VK_SUCCESS) break;
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    if (vkQueueSubmit(c.queue, 1, &si, fence) != VK_SUCCESS) break;
    if (vkWaitForFences(c.device, 1, &fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) break;
    okAll = true;
  } while (false);

  if (fence) vkDestroyFence(c.device, fence, nullptr);
  if (cmd) vkFreeCommandBuffers(c.device, c.pool, 1, &cmd);
  if (descPool) vkDestroyDescriptorPool(c.device, descPool, nullptr);
  if (pipe) vkDestroyPipeline(c.device, pipe, nullptr);
  if (shader) vkDestroyShaderModule(c.device, shader, nullptr);
  vkDestroyPipelineLayout(c.device, layout, nullptr);
  vkDestroyDescriptorSetLayout(c.device, dsl, nullptr);
  return okAll;
}

}  // namespace

bool builtWithVulkan() noexcept { return true; }

int deviceCount() {
  Context c = makeContext();
  return c.ok ? 1 : 0;  // one usable compute device (best pick); enumerateDevices() lists all
}

std::vector<DeviceInfo> enumerateDevices() {
  std::vector<DeviceInfo> out;
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.apiVersion = VK_API_VERSION_1_1;
  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  VkInstance inst = VK_NULL_HANDLE;
  if (vkCreateInstance(&ici, nullptr, &inst) != VK_SUCCESS) return out;

  std::uint32_t n = 0;
  vkEnumeratePhysicalDevices(inst, &n, nullptr);
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(inst, &n, devs.data());
  for (std::uint32_t i = 0; i < n; ++i) {
    VkPhysicalDeviceProperties p{};
    vkGetPhysicalDeviceProperties(devs[i], &p);
    VkPhysicalDeviceMemoryProperties mp{};
    vkGetPhysicalDeviceMemoryProperties(devs[i], &mp);
    std::size_t local = 0;
    for (std::uint32_t h = 0; h < mp.memoryHeapCount; ++h) {
      if (mp.memoryHeaps[h].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT)
        local = std::max<std::size_t>(local, mp.memoryHeaps[h].size);
    }
    DeviceInfo d;
    d.index = static_cast<int>(i);
    d.name = p.deviceName;
    d.apiVersion = p.apiVersion;
    d.vendorID = p.vendorID;
    d.deviceID = p.deviceID;
    d.deviceType = static_cast<int>(p.deviceType);
    d.deviceLocalMem = local;
    out.push_back(std::move(d));
  }
  vkDestroyInstance(inst, nullptr);
  return out;
}

std::optional<DeviceInfo> deviceInfo(int index) {
  auto all = enumerateDevices();
  for (auto& d : all)
    if (d.index == index) return d;
  return std::nullopt;
}

SelfTestResult selfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};

  VkPhysicalDeviceProperties p{};
  vkGetPhysicalDeviceProperties(c.phys, &p);

  // Bring-up: a trivial Q8_0 dispatch that must reproduce a hand-computed value. This exercises the
  // whole path — instance, device, queue, buffers, descriptors, pipeline, submit, readback — so a
  // green result means the compute plumbing works, not just that a device enumerated.
  const int rows = 1, cols = 32;
  std::vector<std::uint8_t> W(34, 0);
  const std::uint16_t hs = encodeHalf(0.5f);
  W[0] = static_cast<std::uint8_t>(hs & 0xFF);
  W[1] = static_cast<std::uint8_t>(hs >> 8);
  const float d = decodeHalf(hs);
  std::vector<float> x(cols), ref(rows, 0.0f);
  double acc = 0.0;
  for (int i = 0; i < cols; ++i) {
    const signed char q = static_cast<signed char>((i % 5) - 2);
    W[2 + i] = static_cast<std::uint8_t>(q);
    x[i] = 0.25f * ((i % 7) - 3);
    acc += d * static_cast<float>(q) * x[i];
  }
  ref[0] = static_cast<float>(acc);

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);  // pad to 4 for the uint[] SSBO
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const std::uint32_t groups = (rows + 63) / 64;
  const bool ran = dispatch(c, qmatmul_q8_0_spv, sizeof(qmatmul_q8_0_spv), {bw.buf, bx.buf, bo.buf},
                            &pc, sizeof(pc), groups);
  std::vector<float> got(rows, 0.0f);
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, "compute dispatch failed"};

  const float err = std::fabs(got[0] - ref[0]);
  if (err > 1e-3f)
    return {true, false, "compute result disagrees with host reference (err " + std::to_string(err) + ")"};
  return {true, true, std::string("compute pipeline OK on ") + p.deviceName};
}

SelfTestResult qmatmulQ8_0SelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  // ---- correctness on a small Q8_0 matrix vs a host reference (mirrors the CUDA self-test) ----
  const int rows = 64, cols = 256;
  const int nBlocks = cols / 32;
  const std::size_t rowBytes = static_cast<std::size_t>(nBlocks) * 34;
  std::vector<std::uint8_t> W(static_cast<std::size_t>(rows) * rowBytes, 0);
  std::vector<float> x(cols), ref(rows, 0.0f), got(rows, 0.0f);
  for (int i = 0; i < cols; ++i) x[i] = 0.1f * ((i % 5) - 2);
  for (int r = 0; r < rows; ++r) {
    double acc = 0.0;
    for (int b = 0; b < nBlocks; ++b) {
      std::uint8_t* blk = W.data() + static_cast<std::size_t>(r) * rowBytes + static_cast<std::size_t>(b) * 34;
      const std::uint16_t hs = encodeHalf(0.02f * ((r % 7) + 1));
      blk[0] = static_cast<std::uint8_t>(hs & 0xFF);
      blk[1] = static_cast<std::uint8_t>(hs >> 8);
      const float d = decodeHalf(hs);  // rounded scale so the reference matches the shader
      for (int i = 0; i < 32; ++i) {
        const signed char q = static_cast<signed char>(((r + b + i) % 15) - 7);
        blk[2 + i] = static_cast<std::uint8_t>(q);
        acc += d * static_cast<float>(q) * x[b * 32 + i];
      }
    }
    ref[r] = static_cast<float>(acc);
  }

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const bool ran = dispatch(c, qmatmul_q8_0_spv, sizeof(qmatmul_q8_0_spv), {bw.buf, bx.buf, bo.buf},
                            &pc, sizeof(pc), (rows + 63) / 64);
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, "qmatmul dispatch failed"};

  float maxErr = 0.0f;
  for (int r = 0; r < rows; ++r) maxErr = std::max(maxErr, std::fabs(got[r] - ref[r]));
  if (maxErr > 1e-2f)
    return {true, false, "Vulkan qmatmul disagrees with host reference (max err " +
                             std::to_string(maxErr) + ")"};

  return {true, true, std::string("Vulkan Q8_0 matmul matches host reference (max err ") +
                          std::to_string(maxErr) + ") on " + dp.deviceName};
}

// Shared driver for a K-quant (Q4_K / Q6_K) GEMV self-test: builds a synthetic weight matrix and a
// host reference with `ref`, runs `spirv` on the device, and compares. `blockBytes` is the super-
// block size (144 for Q4_K, 210 for Q6_K), `fill` populates one super-block's bytes given (r, sb).
SelfTestResult kQuantSelfTest(const char* label, const std::uint32_t* spirv, std::size_t spirvBytes,
                              int blockBytes,
                              const std::function<void(int r, int sb, std::uint8_t* blk,
                                                       const std::vector<float>& x, double& acc)>& fill) {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  const int rows = 48, cols = 512;  // 2 super-blocks/row
  const int nSB = cols / 256;
  const std::size_t rowBytes = static_cast<std::size_t>(nSB) * blockBytes;
  std::vector<std::uint8_t> W(static_cast<std::size_t>(rows) * rowBytes, 0);
  std::vector<float> x(cols), ref(rows, 0.0f), got(rows, 0.0f);
  for (int i = 0; i < cols; ++i) x[i] = 0.05f * ((i % 13) - 6);
  for (int r = 0; r < rows; ++r) {
    double acc = 0.0;
    for (int sb = 0; sb < nSB; ++sb) {
      std::uint8_t* blk = W.data() + static_cast<std::size_t>(r) * rowBytes +
                          static_cast<std::size_t>(sb) * blockBytes;
      fill(r, sb, blk, x, acc);
    }
    ref[r] = static_cast<float>(acc);
  }

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const bool ran =
      dispatch(c, spirv, spirvBytes, {bw.buf, bx.buf, bo.buf}, &pc, sizeof(pc), (rows + 63) / 64);
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, std::string(label) + " dispatch failed"};

  float maxErr = 0.0f, ref2 = 0.0f;
  for (int r = 0; r < rows; ++r) {
    maxErr = std::max(maxErr, std::fabs(got[r] - ref[r]));
    ref2 = std::max(ref2, std::fabs(ref[r]));
  }
  const float tol = 1e-2f * (1.0f + ref2);  // scale tolerance to the magnitude of the reference
  if (maxErr > tol)
    return {true, false, std::string(label) + " disagrees with host reference (max err " +
                             std::to_string(maxErr) + ")"};
  return {true, true, std::string(label) + " matches host reference (max err " +
                          std::to_string(maxErr) + ") on " + dp.deviceName};
}

SelfTestResult qmatmulQ4_KSelfTest() {
  return kQuantSelfTest(
      "Vulkan Q4_K matmul", qmatmul_q4_k_spv, sizeof(qmatmul_q4_k_spv), 144,
      [](int r, int sb, std::uint8_t* blk, const std::vector<float>& x, double& acc) {
        const std::uint16_t dh = encodeHalf(0.015f * ((r % 5) + 1));
        const std::uint16_t mh = encodeHalf(0.007f * ((sb % 3) + 1));
        blk[0] = dh & 0xFF;
        blk[1] = dh >> 8;
        blk[2] = mh & 0xFF;
        blk[3] = mh >> 8;
        for (int i = 0; i < 12; ++i) blk[4 + i] = static_cast<std::uint8_t>((r * 7 + sb * 3 + i * 11) & 0x3F);
        std::uint8_t* qs = blk + 16;
        for (int i = 0; i < 128; ++i) qs[i] = static_cast<std::uint8_t>((r + sb + i * 5) & 0xFF);
        const float d = decodeHalf(dh), dmin = decodeHalf(mh);
        for (int j = 0; j < 8; ++j) {
          unsigned char sc, m;
          getScaleMinK4(j, blk + 4, sc, m);
          for (int t = 0; t < 32; ++t) {
            const int i = j * 32 + t;
            const int chunk = i / 64, local = i % 64;
            const std::uint8_t qbyte = qs[chunk * 32 + (local & 31)];
            const int nib = (local < 32) ? (qbyte & 0xF) : (qbyte >> 4);
            acc += (d * sc * nib - dmin * m) * x[static_cast<std::size_t>(sb) * 256 + i];
          }
        }
      });
}

SelfTestResult qmatmulQ6_KSelfTest() {
  return kQuantSelfTest(
      "Vulkan Q6_K matmul", qmatmul_q6_k_spv, sizeof(qmatmul_q6_k_spv), 210,
      [](int r, int sb, std::uint8_t* blk, const std::vector<float>& x, double& acc) {
        std::uint8_t* ql = blk;
        std::uint8_t* qh = blk + 128;
        signed char* sc = reinterpret_cast<signed char*>(blk + 192);
        for (int i = 0; i < 128; ++i) ql[i] = static_cast<std::uint8_t>((r + sb + i * 3) & 0xFF);
        for (int i = 0; i < 64; ++i) qh[i] = static_cast<std::uint8_t>((r * 2 + sb + i * 7) & 0xFF);
        for (int i = 0; i < 16; ++i) sc[i] = static_cast<signed char>(((r + sb + i * 5) % 25) - 12);
        const std::uint16_t dh = encodeHalf(0.012f * ((r % 6) + 1));
        blk[208] = dh & 0xFF;
        blk[209] = dh >> 8;
        const float d = decodeHalf(dh);
        for (int i = 0; i < 256; ++i) {
          const int hlf = i >> 7, p = i & 127, l = p & 31, quarter = p >> 5, isub = l >> 4;
          const std::uint8_t* qlh = ql + hlf * 64;
          const std::uint8_t* qhh = qh + hlf * 32;
          int lo, hi;
          if (quarter == 0) { lo = qlh[l] & 0xF;      hi = (qhh[l] >> 0) & 3; }
          else if (quarter == 1) { lo = qlh[l + 32] & 0xF; hi = (qhh[l] >> 2) & 3; }
          else if (quarter == 2) { lo = qlh[l] >> 4;   hi = (qhh[l] >> 4) & 3; }
          else { lo = qlh[l + 32] >> 4;                hi = (qhh[l] >> 6) & 3; }
          const int q = (lo | (hi << 4)) - 32;
          const int scv = sc[hlf * 8 + isub + quarter * 2];
          acc += d * scv * q * x[static_cast<std::size_t>(sb) * 256 + i];
        }
      });
}

SelfTestResult opsSelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  float maxErr = 0.0f;
  auto track = [&](const std::vector<float>& a, const std::vector<float>& b) {
    for (std::size_t i = 0; i < a.size(); ++i) maxErr = std::max(maxErr, std::fabs(a[i] - b[i]));
  };
  const char* failed = nullptr;

  // RMSNorm: bindings {out, x, w}, one workgroup.
  {
    const int n = 512;
    std::vector<float> x(n), w(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) {
      x[i] = 0.01f * ((i % 13) - 6);
      w[i] = 0.5f + 0.001f * i;
    }
    double sq = 0.0;
    for (float v : x) sq += static_cast<double>(v) * v;
    const float scale = 1.0f / std::sqrt(static_cast<float>(sq / n) + 1e-5f);
    for (int i = 0; i < n; ++i) ref[i] = x[i] * scale * w[i];
    Buffer bo{}, bx{}, bw{};
    if (makeBuffer(c, n * sizeof(float), bo) && makeBuffer(c, n * sizeof(float), bx) &&
        makeBuffer(c, n * sizeof(float), bw)) {
      upload(bx, x.data(), n * sizeof(float));
      upload(bw, w.data(), n * sizeof(float));
      struct {
        std::uint32_t n;
        float eps;
      } pc{static_cast<std::uint32_t>(n), 1e-5f};
      if (dispatch(c, rmsnorm_spv, sizeof(rmsnorm_spv), {bo.buf, bx.buf, bw.buf}, &pc, sizeof(pc), 1)) {
        download(bo, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "rmsnorm";
      }
    } else {
      failed = "rmsnorm alloc";
    }
    bo.destroy();
    bx.destroy();
    bw.destroy();
  }

  // RoPE (NeoX): binding {v} in place.
  if (!failed) {
    const int nH = 4, hd = 8, half = hd / 2, pos = 3, n = nH * hd;
    const float base = 10000.0f;
    std::vector<float> v(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) v[i] = 0.1f * ((i % 7) - 3);
    ref = v;
    for (int h = 0; h < nH; ++h)
      for (int i = 0; i < half; ++i) {
        const float theta = pos * std::pow(base, -2.0f * i / hd);
        const float cc = std::cos(theta), ss = std::sin(theta);
        const float a = ref[h * hd + i], b = ref[h * hd + i + half];
        ref[h * hd + i] = a * cc - b * ss;
        ref[h * hd + i + half] = a * ss + b * cc;
      }
    Buffer bv{};
    if (makeBuffer(c, n * sizeof(float), bv)) {
      upload(bv, v.data(), n * sizeof(float));
      struct {
        std::uint32_t nHeads, headDim;
        std::int32_t pos;
        float freqBase;
      } pc{static_cast<std::uint32_t>(nH), static_cast<std::uint32_t>(hd), pos, base};
      if (dispatch(c, rope_spv, sizeof(rope_spv), {bv.buf}, &pc, sizeof(pc),
                   static_cast<std::uint32_t>((nH * half + 63) / 64))) {
        download(bv, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "rope";
      }
    } else {
      failed = "rope alloc";
    }
    bv.destroy();
  }

  // SwiGLU: bindings {out, gate, up}.
  if (!failed) {
    const int n = 1000;
    std::vector<float> g(n), u(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) {
      g[i] = 0.02f * ((i % 11) - 5);
      u[i] = 0.03f * ((i % 9) - 4);
      ref[i] = (g[i] / (1.0f + std::exp(-g[i]))) * u[i];
    }
    Buffer bo{}, bg{}, bu{};
    if (makeBuffer(c, n * sizeof(float), bo) && makeBuffer(c, n * sizeof(float), bg) &&
        makeBuffer(c, n * sizeof(float), bu)) {
      upload(bg, g.data(), n * sizeof(float));
      upload(bu, u.data(), n * sizeof(float));
      struct {
        std::uint32_t n;
      } pc{static_cast<std::uint32_t>(n)};
      if (dispatch(c, swiglu_spv, sizeof(swiglu_spv), {bo.buf, bg.buf, bu.buf}, &pc, sizeof(pc),
                   static_cast<std::uint32_t>((n + 255) / 256))) {
        download(bo, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "swiglu";
      }
    } else {
      failed = "swiglu alloc";
    }
    bo.destroy();
    bg.destroy();
    bu.destroy();
  }

  // Residual add: binding {out(=a, in place), x(=b)}.
  if (!failed) {
    const int n = 1000;
    std::vector<float> a(n), b(n), ref(n), got(n);
    for (int i = 0; i < n; ++i) {
      a[i] = 0.1f * i;
      b[i] = -0.05f * i;
      ref[i] = a[i] + b[i];
    }
    Buffer ba{}, bb{};
    if (makeBuffer(c, n * sizeof(float), ba) && makeBuffer(c, n * sizeof(float), bb)) {
      upload(ba, a.data(), n * sizeof(float));
      upload(bb, b.data(), n * sizeof(float));
      struct {
        std::uint32_t n;
      } pc{static_cast<std::uint32_t>(n)};
      if (dispatch(c, add_spv, sizeof(add_spv), {ba.buf, bb.buf}, &pc, sizeof(pc),
                   static_cast<std::uint32_t>((n + 255) / 256))) {
        download(ba, got.data(), n * sizeof(float));
        track(ref, got);
      } else {
        failed = "add";
      }
    } else {
      failed = "add alloc";
    }
    ba.destroy();
    bb.destroy();
  }

  if (failed) return {true, false, std::string(failed) + " dispatch failed"};
  const bool ok = maxErr < 1e-3f;
  return {true, ok,
          (ok ? "rmsnorm/rope/swiglu/add match CPU (max err " : "Vulkan ops disagree with CPU (max err ") +
              std::to_string(maxErr) + ") on " + dp.deviceName};
}

SelfTestResult attentionSelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  // GQA: 4 query heads, 2 kv heads, head_dim 8, 5 cached positions (matches the CUDA self-test).
  const int nHeads = 4, nKv = 2, headDim = 8, seqLen = 5;
  const int kvDim = nKv * headDim;
  const int group = nHeads / nKv;
  std::vector<float> q(static_cast<std::size_t>(nHeads) * headDim);
  std::vector<float> K(static_cast<std::size_t>(seqLen) * kvDim);
  std::vector<float> V(static_cast<std::size_t>(seqLen) * kvDim);
  for (std::size_t i = 0; i < q.size(); ++i) q[i] = 0.05f * ((i % 11) - 5);
  for (std::size_t i = 0; i < K.size(); ++i) K[i] = 0.03f * ((i % 13) - 6);
  for (std::size_t i = 0; i < V.size(); ++i) V[i] = 0.04f * ((i % 7) - 3);

  std::vector<float> ref(static_cast<std::size_t>(nHeads) * headDim, 0.0f), got(ref.size());
  const float invSqrt = 1.0f / std::sqrt(static_cast<float>(headDim));
  for (int h = 0; h < nHeads; ++h) {
    const int kvHead = h / group;
    std::vector<float> sc(seqLen);
    for (int t = 0; t < seqLen; ++t) {
      float dot = 0.0f;
      for (int d = 0; d < headDim; ++d)
        dot += q[h * headDim + d] * K[t * kvDim + kvHead * headDim + d];
      sc[t] = dot * invSqrt;
    }
    float mx = sc[0];
    for (int t = 1; t < seqLen; ++t) mx = std::max(mx, sc[t]);
    float sum = 0.0f;
    for (int t = 0; t < seqLen; ++t) {
      sc[t] = std::exp(sc[t] - mx);
      sum += sc[t];
    }
    for (int d = 0; d < headDim; ++d) {
      float acc = 0.0f;
      for (int t = 0; t < seqLen; ++t)
        acc += (sc[t] / sum) * V[t * kvDim + kvHead * headDim + d];
      ref[h * headDim + d] = acc;
    }
  }

  Buffer bo{}, bq{}, bk{}, bv{};
  if (!makeBuffer(c, got.size() * sizeof(float), bo) || !makeBuffer(c, q.size() * sizeof(float), bq) ||
      !makeBuffer(c, K.size() * sizeof(float), bk) || !makeBuffer(c, V.size() * sizeof(float), bv)) {
    bo.destroy();
    bq.destroy();
    bk.destroy();
    bv.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bq, q.data(), q.size() * sizeof(float));
  upload(bk, K.data(), K.size() * sizeof(float));
  upload(bv, V.data(), V.size() * sizeof(float));
  struct {
    std::uint32_t nHeads, nKv, headDim, seqLen, kvDim;
  } pc{static_cast<std::uint32_t>(nHeads), static_cast<std::uint32_t>(nKv),
       static_cast<std::uint32_t>(headDim), static_cast<std::uint32_t>(seqLen),
       static_cast<std::uint32_t>(kvDim)};
  const bool ran = dispatch(c, attention_spv, sizeof(attention_spv), {bo.buf, bq.buf, bk.buf, bv.buf},
                            &pc, sizeof(pc), static_cast<std::uint32_t>(nHeads));
  if (ran) download(bo, got.data(), got.size() * sizeof(float));
  bo.destroy();
  bq.destroy();
  bk.destroy();
  bv.destroy();
  if (!ran) return {true, false, "attention dispatch failed"};

  float maxErr = 0.0f;
  for (std::size_t i = 0; i < ref.size(); ++i) maxErr = std::max(maxErr, std::fabs(got[i] - ref[i]));
  const bool ok = maxErr < 1e-3f;
  return {true, ok,
          (ok ? "GQA decode attention matches CPU (max err " : "attention disagrees with CPU (max err ") +
              std::to_string(maxErr) + ") on " + dp.deviceName};
}

}  // namespace qorvix::vulkan
