// Real Vulkan compute backend. Compiled only when QORVIX_ENABLE_VULKAN is ON and the Vulkan loader
// + a GLSL->SPIR-V compiler were found (see vulkan/CMakeLists.txt). Provides the same facade as the
// CUDA backend so the CLI/tests drive either without #ifdefs.
//
// Design: correctness-first, headless-verifiable. All buffers are HOST_VISIBLE|HOST_COHERENT so a
// dispatch is upload -> record -> submit -> wait -> read with no staging; this runs identically on
// Mesa's software device (lavapipe) — where the argmax-parity gate is checked with no physical GPU
// — and on real NVIDIA/AMD/Apple/Intel hardware (device-local + staging is a later throughput
// milestone, not a correctness one). The compute shaders are SPIR-V embedded at build time.
#include "qorvix/vulkan/backend.hpp"

#include <vulkan/vulkan.h>

#include <cmath>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

#include "qmatmul_q8_0_spv.h"  // const uint32_t qmatmul_q8_0_spv[] — generated by glslang

namespace qorvix::vulkan {
namespace {

// fp16 (IEEE half) <-> float, matching the GGUF scale encoding the shader decodes with
// unpackHalf2x16. Kept on the host so the reference and the shader agree bit-for-bit on the scale.
float decodeHalf(std::uint16_t h) {
  const std::uint32_t sign = (h & 0x8000u) << 16;
  const std::uint32_t exp = (h >> 10) & 0x1F;
  const std::uint32_t mant = h & 0x3FF;
  std::uint32_t bits;
  if (exp == 0) {
    if (mant == 0) {
      bits = sign;  // +/- zero
    } else {
      // subnormal half -> normalized float
      int e = -1;
      std::uint32_t m = mant;
      do {
        m <<= 1;
        ++e;
      } while ((m & 0x400u) == 0);
      m &= 0x3FFu;
      bits = sign | ((127 - 15 - e) << 23) | (m << 13);
    }
  } else if (exp == 0x1F) {
    bits = sign | 0x7F800000u | (mant << 13);  // inf/nan
  } else {
    bits = sign | ((exp - 15 + 127) << 23) | (mant << 13);
  }
  float f;
  std::memcpy(&f, &bits, 4);
  return f;
}

std::uint16_t encodeHalf(float f) {
  std::uint32_t x;
  std::memcpy(&x, &f, 4);
  const std::uint32_t sign = (x >> 16) & 0x8000u;
  std::int32_t exp = static_cast<std::int32_t>((x >> 23) & 0xFF) - 127 + 15;
  std::uint32_t mant = x & 0x7FFFFFu;
  if (exp <= 0) return static_cast<std::uint16_t>(sign);          // flush tiny to zero (sufficient here)
  if (exp >= 0x1F) return static_cast<std::uint16_t>(sign | 0x7C00u);  // overflow -> inf
  return static_cast<std::uint16_t>(sign | (exp << 10) | (mant >> 13));
}

// ---- minimal Vulkan compute context ---------------------------------------------------------
struct Context {
  VkInstance instance = VK_NULL_HANDLE;
  VkPhysicalDevice phys = VK_NULL_HANDLE;
  VkDevice device = VK_NULL_HANDLE;
  VkQueue queue = VK_NULL_HANDLE;
  std::uint32_t queueFamily = 0;
  VkCommandPool pool = VK_NULL_HANDLE;
  VkPhysicalDeviceMemoryProperties memProps{};
  bool ok = false;

  ~Context() {
    if (device) {
      if (pool) vkDestroyCommandPool(device, pool, nullptr);
      vkDestroyDevice(device, nullptr);
    }
    if (instance) vkDestroyInstance(instance, nullptr);
  }
};

// Pick a queue family that supports compute.
bool findComputeQueue(VkPhysicalDevice phys, std::uint32_t& family) {
  std::uint32_t n = 0;
  vkGetPhysicalDeviceQueueFamilyProperties(phys, &n, nullptr);
  std::vector<VkQueueFamilyProperties> qf(n);
  vkGetPhysicalDeviceQueueFamilyProperties(phys, &n, qf.data());
  for (std::uint32_t i = 0; i < n; ++i) {
    if (qf[i].queueFlags & VK_QUEUE_COMPUTE_BIT) {
      family = i;
      return true;
    }
  }
  return false;
}

// Prefer a discrete GPU, then integrated, then anything (incl. the CPU software device).
VkPhysicalDevice pickPhysical(VkInstance inst) {
  std::uint32_t n = 0;
  vkEnumeratePhysicalDevices(inst, &n, nullptr);
  if (n == 0) return VK_NULL_HANDLE;
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(inst, &n, devs.data());
  VkPhysicalDevice best = VK_NULL_HANDLE;
  int bestRank = -1;
  for (auto d : devs) {
    VkPhysicalDeviceProperties p{};
    vkGetPhysicalDeviceProperties(d, &p);
    int rank = 0;
    switch (p.deviceType) {
      case VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU: rank = 4; break;
      case VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU: rank = 3; break;
      case VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU: rank = 2; break;
      case VK_PHYSICAL_DEVICE_TYPE_CPU: rank = 1; break;
      default: rank = 0; break;
    }
    std::uint32_t fam = 0;
    if (rank > bestRank && findComputeQueue(d, fam)) {
      best = d;
      bestRank = rank;
    }
  }
  return best;
}

Context makeContext() {
  Context c;
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.pApplicationName = "qorvix";
  app.apiVersion = VK_API_VERSION_1_1;

  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  if (vkCreateInstance(&ici, nullptr, &c.instance) != VK_SUCCESS) return c;

  c.phys = pickPhysical(c.instance);
  if (!c.phys) return c;
  if (!findComputeQueue(c.phys, c.queueFamily)) return c;
  vkGetPhysicalDeviceMemoryProperties(c.phys, &c.memProps);

  const float prio = 1.0f;
  VkDeviceQueueCreateInfo qci{};
  qci.sType = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO;
  qci.queueFamilyIndex = c.queueFamily;
  qci.queueCount = 1;
  qci.pQueuePriorities = &prio;

  VkDeviceCreateInfo dci{};
  dci.sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO;
  dci.queueCreateInfoCount = 1;
  dci.pQueueCreateInfos = &qci;
  if (vkCreateDevice(c.phys, &dci, nullptr, &c.device) != VK_SUCCESS) return c;
  vkGetDeviceQueue(c.device, c.queueFamily, 0, &c.queue);

  VkCommandPoolCreateInfo pci{};
  pci.sType = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO;
  pci.queueFamilyIndex = c.queueFamily;
  if (vkCreateCommandPool(c.device, &pci, nullptr, &c.pool) != VK_SUCCESS) return c;

  c.ok = true;
  return c;
}

std::uint32_t findMemType(const Context& c, std::uint32_t typeBits, VkMemoryPropertyFlags want) {
  for (std::uint32_t i = 0; i < c.memProps.memoryTypeCount; ++i) {
    if ((typeBits & (1u << i)) && (c.memProps.memoryTypes[i].propertyFlags & want) == want) return i;
  }
  return UINT32_MAX;
}

// A host-visible, coherent storage buffer. Correctness-first: no staging, map/unmap directly.
struct Buffer {
  VkDevice device = VK_NULL_HANDLE;
  VkBuffer buf = VK_NULL_HANDLE;
  VkDeviceMemory mem = VK_NULL_HANDLE;
  VkDeviceSize size = 0;

  void destroy() {
    if (buf) vkDestroyBuffer(device, buf, nullptr);
    if (mem) vkFreeMemory(device, mem, nullptr);
    buf = VK_NULL_HANDLE;
    mem = VK_NULL_HANDLE;
  }
};

bool makeBuffer(const Context& c, VkDeviceSize size, Buffer& out) {
  out.device = c.device;
  out.size = size;
  VkBufferCreateInfo bci{};
  bci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
  bci.size = size;
  bci.usage = VK_BUFFER_USAGE_STORAGE_BUFFER_BIT;
  bci.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
  if (vkCreateBuffer(c.device, &bci, nullptr, &out.buf) != VK_SUCCESS) return false;

  VkMemoryRequirements req{};
  vkGetBufferMemoryRequirements(c.device, out.buf, &req);
  const std::uint32_t mt = findMemType(
      c, req.memoryTypeBits, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);
  if (mt == UINT32_MAX) return false;

  VkMemoryAllocateInfo mai{};
  mai.sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO;
  mai.allocationSize = req.size;
  mai.memoryTypeIndex = mt;
  if (vkAllocateMemory(c.device, &mai, nullptr, &out.mem) != VK_SUCCESS) return false;
  return vkBindBufferMemory(c.device, out.buf, out.mem, 0) == VK_SUCCESS;
}

bool upload(const Buffer& b, const void* src, VkDeviceSize n) {
  void* p = nullptr;
  if (vkMapMemory(b.device, b.mem, 0, n, 0, &p) != VK_SUCCESS) return false;
  std::memcpy(p, src, n);
  vkUnmapMemory(b.device, b.mem);
  return true;
}

bool download(const Buffer& b, void* dst, VkDeviceSize n) {
  void* p = nullptr;
  if (vkMapMemory(b.device, b.mem, 0, n, 0, &p) != VK_SUCCESS) return false;
  std::memcpy(dst, p, n);
  vkUnmapMemory(b.device, b.mem);
  return true;
}

// One-shot compute pipeline over N storage-buffer bindings with a push-constant block. Builds the
// pipeline, dispatches `groups` workgroups, and waits. Returns false on any Vulkan error.
bool dispatch(const Context& c, const std::uint32_t* spirv, std::size_t spirvBytes,
              const std::vector<VkBuffer>& buffers, const void* push, std::uint32_t pushSize,
              std::uint32_t groups) {
  const std::uint32_t nb = static_cast<std::uint32_t>(buffers.size());

  std::vector<VkDescriptorSetLayoutBinding> binds(nb);
  for (std::uint32_t i = 0; i < nb; ++i) {
    binds[i] = {i, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};
  }
  VkDescriptorSetLayoutCreateInfo dslci{};
  dslci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;
  dslci.bindingCount = nb;
  dslci.pBindings = binds.data();
  VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
  if (vkCreateDescriptorSetLayout(c.device, &dslci, nullptr, &dsl) != VK_SUCCESS) return false;

  VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize};
  VkPipelineLayoutCreateInfo plci{};
  plci.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
  plci.setLayoutCount = 1;
  plci.pSetLayouts = &dsl;
  plci.pushConstantRangeCount = pushSize ? 1 : 0;
  plci.pPushConstantRanges = pushSize ? &pcr : nullptr;
  VkPipelineLayout layout = VK_NULL_HANDLE;
  if (vkCreatePipelineLayout(c.device, &plci, nullptr, &layout) != VK_SUCCESS) {
    vkDestroyDescriptorSetLayout(c.device, dsl, nullptr);
    return false;
  }

  VkShaderModuleCreateInfo smci{};
  smci.sType = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO;
  smci.codeSize = spirvBytes;
  smci.pCode = spirv;
  VkShaderModule shader = VK_NULL_HANDLE;
  bool okAll = false;
  VkPipeline pipe = VK_NULL_HANDLE;
  VkDescriptorPool descPool = VK_NULL_HANDLE;
  VkCommandBuffer cmd = VK_NULL_HANDLE;
  VkFence fence = VK_NULL_HANDLE;
  do {
    if (vkCreateShaderModule(c.device, &smci, nullptr, &shader) != VK_SUCCESS) break;

    VkPipelineShaderStageCreateInfo stage{};
    stage.sType = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO;
    stage.stage = VK_SHADER_STAGE_COMPUTE_BIT;
    stage.module = shader;
    stage.pName = "main";
    VkComputePipelineCreateInfo cpci{};
    cpci.sType = VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO;
    cpci.stage = stage;
    cpci.layout = layout;
    if (vkCreateComputePipelines(c.device, VK_NULL_HANDLE, 1, &cpci, nullptr, &pipe) != VK_SUCCESS)
      break;

    VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nb};
    VkDescriptorPoolCreateInfo dpci{};
    dpci.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;
    dpci.maxSets = 1;
    dpci.poolSizeCount = 1;
    dpci.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(c.device, &dpci, nullptr, &descPool) != VK_SUCCESS) break;

    VkDescriptorSetAllocateInfo dsai{};
    dsai.sType = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO;
    dsai.descriptorPool = descPool;
    dsai.descriptorSetCount = 1;
    dsai.pSetLayouts = &dsl;
    VkDescriptorSet set = VK_NULL_HANDLE;
    if (vkAllocateDescriptorSets(c.device, &dsai, &set) != VK_SUCCESS) break;

    std::vector<VkDescriptorBufferInfo> dbi(nb);
    std::vector<VkWriteDescriptorSet> writes(nb);
    for (std::uint32_t i = 0; i < nb; ++i) {
      dbi[i] = {buffers[i], 0, VK_WHOLE_SIZE};
      writes[i] = {};
      writes[i].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
      writes[i].dstSet = set;
      writes[i].dstBinding = i;
      writes[i].descriptorCount = 1;
      writes[i].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
      writes[i].pBufferInfo = &dbi[i];
    }
    vkUpdateDescriptorSets(c.device, nb, writes.data(), 0, nullptr);

    VkCommandBufferAllocateInfo cbai{};
    cbai.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO;
    cbai.commandPool = c.pool;
    cbai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cbai.commandBufferCount = 1;
    if (vkAllocateCommandBuffers(c.device, &cbai, &cmd) != VK_SUCCESS) break;

    VkCommandBufferBeginInfo bi{};
    bi.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(cmd, &bi);
    vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipe);
    vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_COMPUTE, layout, 0, 1, &set, 0, nullptr);
    if (pushSize) vkCmdPushConstants(cmd, layout, VK_SHADER_STAGE_COMPUTE_BIT, 0, pushSize, push);
    vkCmdDispatch(cmd, groups, 1, 1);
    vkEndCommandBuffer(cmd);

    VkFenceCreateInfo fci{};
    fci.sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO;
    if (vkCreateFence(c.device, &fci, nullptr, &fence) != VK_SUCCESS) break;
    VkSubmitInfo si{};
    si.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO;
    si.commandBufferCount = 1;
    si.pCommandBuffers = &cmd;
    if (vkQueueSubmit(c.queue, 1, &si, fence) != VK_SUCCESS) break;
    if (vkWaitForFences(c.device, 1, &fence, VK_TRUE, UINT64_MAX) != VK_SUCCESS) break;
    okAll = true;
  } while (false);

  if (fence) vkDestroyFence(c.device, fence, nullptr);
  if (cmd) vkFreeCommandBuffers(c.device, c.pool, 1, &cmd);
  if (descPool) vkDestroyDescriptorPool(c.device, descPool, nullptr);
  if (pipe) vkDestroyPipeline(c.device, pipe, nullptr);
  if (shader) vkDestroyShaderModule(c.device, shader, nullptr);
  vkDestroyPipelineLayout(c.device, layout, nullptr);
  vkDestroyDescriptorSetLayout(c.device, dsl, nullptr);
  return okAll;
}

}  // namespace

bool builtWithVulkan() noexcept { return true; }

int deviceCount() {
  Context c = makeContext();
  return c.ok ? 1 : 0;  // one usable compute device (best pick); enumerateDevices() lists all
}

std::vector<DeviceInfo> enumerateDevices() {
  std::vector<DeviceInfo> out;
  VkApplicationInfo app{};
  app.sType = VK_STRUCTURE_TYPE_APPLICATION_INFO;
  app.apiVersion = VK_API_VERSION_1_1;
  VkInstanceCreateInfo ici{};
  ici.sType = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;
  ici.pApplicationInfo = &app;
  VkInstance inst = VK_NULL_HANDLE;
  if (vkCreateInstance(&ici, nullptr, &inst) != VK_SUCCESS) return out;

  std::uint32_t n = 0;
  vkEnumeratePhysicalDevices(inst, &n, nullptr);
  std::vector<VkPhysicalDevice> devs(n);
  vkEnumeratePhysicalDevices(inst, &n, devs.data());
  for (std::uint32_t i = 0; i < n; ++i) {
    VkPhysicalDeviceProperties p{};
    vkGetPhysicalDeviceProperties(devs[i], &p);
    VkPhysicalDeviceMemoryProperties mp{};
    vkGetPhysicalDeviceMemoryProperties(devs[i], &mp);
    std::size_t local = 0;
    for (std::uint32_t h = 0; h < mp.memoryHeapCount; ++h) {
      if (mp.memoryHeaps[h].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT)
        local = std::max<std::size_t>(local, mp.memoryHeaps[h].size);
    }
    DeviceInfo d;
    d.index = static_cast<int>(i);
    d.name = p.deviceName;
    d.apiVersion = p.apiVersion;
    d.vendorID = p.vendorID;
    d.deviceID = p.deviceID;
    d.deviceType = static_cast<int>(p.deviceType);
    d.deviceLocalMem = local;
    out.push_back(std::move(d));
  }
  vkDestroyInstance(inst, nullptr);
  return out;
}

std::optional<DeviceInfo> deviceInfo(int index) {
  auto all = enumerateDevices();
  for (auto& d : all)
    if (d.index == index) return d;
  return std::nullopt;
}

SelfTestResult selfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};

  VkPhysicalDeviceProperties p{};
  vkGetPhysicalDeviceProperties(c.phys, &p);

  // Bring-up: a trivial Q8_0 dispatch that must reproduce a hand-computed value. This exercises the
  // whole path — instance, device, queue, buffers, descriptors, pipeline, submit, readback — so a
  // green result means the compute plumbing works, not just that a device enumerated.
  const int rows = 1, cols = 32;
  std::vector<std::uint8_t> W(34, 0);
  const std::uint16_t hs = encodeHalf(0.5f);
  W[0] = static_cast<std::uint8_t>(hs & 0xFF);
  W[1] = static_cast<std::uint8_t>(hs >> 8);
  const float d = decodeHalf(hs);
  std::vector<float> x(cols), ref(rows, 0.0f);
  double acc = 0.0;
  for (int i = 0; i < cols; ++i) {
    const signed char q = static_cast<signed char>((i % 5) - 2);
    W[2 + i] = static_cast<std::uint8_t>(q);
    x[i] = 0.25f * ((i % 7) - 3);
    acc += d * static_cast<float>(q) * x[i];
  }
  ref[0] = static_cast<float>(acc);

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);  // pad to 4 for the uint[] SSBO
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const std::uint32_t groups = (rows + 63) / 64;
  const bool ran = dispatch(c, qmatmul_q8_0_spv, sizeof(qmatmul_q8_0_spv), {bw.buf, bx.buf, bo.buf},
                            &pc, sizeof(pc), groups);
  std::vector<float> got(rows, 0.0f);
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, "compute dispatch failed"};

  const float err = std::fabs(got[0] - ref[0]);
  if (err > 1e-3f)
    return {true, false, "compute result disagrees with host reference (err " + std::to_string(err) + ")"};
  return {true, true, std::string("compute pipeline OK on ") + p.deviceName};
}

SelfTestResult qmatmulQ8_0SelfTest() {
  Context c = makeContext();
  if (!c.ok) return {false, false, "no Vulkan device present"};
  VkPhysicalDeviceProperties dp{};
  vkGetPhysicalDeviceProperties(c.phys, &dp);

  // ---- correctness on a small Q8_0 matrix vs a host reference (mirrors the CUDA self-test) ----
  const int rows = 64, cols = 256;
  const int nBlocks = cols / 32;
  const std::size_t rowBytes = static_cast<std::size_t>(nBlocks) * 34;
  std::vector<std::uint8_t> W(static_cast<std::size_t>(rows) * rowBytes, 0);
  std::vector<float> x(cols), ref(rows, 0.0f), got(rows, 0.0f);
  for (int i = 0; i < cols; ++i) x[i] = 0.1f * ((i % 5) - 2);
  for (int r = 0; r < rows; ++r) {
    double acc = 0.0;
    for (int b = 0; b < nBlocks; ++b) {
      std::uint8_t* blk = W.data() + static_cast<std::size_t>(r) * rowBytes + static_cast<std::size_t>(b) * 34;
      const std::uint16_t hs = encodeHalf(0.02f * ((r % 7) + 1));
      blk[0] = static_cast<std::uint8_t>(hs & 0xFF);
      blk[1] = static_cast<std::uint8_t>(hs >> 8);
      const float d = decodeHalf(hs);  // rounded scale so the reference matches the shader
      for (int i = 0; i < 32; ++i) {
        const signed char q = static_cast<signed char>(((r + b + i) % 15) - 7);
        blk[2 + i] = static_cast<std::uint8_t>(q);
        acc += d * static_cast<float>(q) * x[b * 32 + i];
      }
    }
    ref[r] = static_cast<float>(acc);
  }

  const VkDeviceSize wBytes = (W.size() + 3) & ~VkDeviceSize(3);
  Buffer bw{}, bx{}, bo{};
  if (!makeBuffer(c, wBytes, bw) || !makeBuffer(c, cols * sizeof(float), bx) ||
      !makeBuffer(c, rows * sizeof(float), bo)) {
    bw.destroy();
    bx.destroy();
    bo.destroy();
    return {true, false, "buffer allocation failed"};
  }
  upload(bw, W.data(), W.size());
  upload(bx, x.data(), cols * sizeof(float));
  struct {
    std::uint32_t rows, cols;
  } pc{static_cast<std::uint32_t>(rows), static_cast<std::uint32_t>(cols)};
  const bool ran = dispatch(c, qmatmul_q8_0_spv, sizeof(qmatmul_q8_0_spv), {bw.buf, bx.buf, bo.buf},
                            &pc, sizeof(pc), (rows + 63) / 64);
  if (ran) download(bo, got.data(), rows * sizeof(float));
  bw.destroy();
  bx.destroy();
  bo.destroy();
  if (!ran) return {true, false, "qmatmul dispatch failed"};

  float maxErr = 0.0f;
  for (int r = 0; r < rows; ++r) maxErr = std::max(maxErr, std::fabs(got[r] - ref[r]));
  if (maxErr > 1e-2f)
    return {true, false, "Vulkan qmatmul disagrees with host reference (max err " +
                             std::to_string(maxErr) + ")"};

  return {true, true, std::string("Vulkan Q8_0 matmul matches host reference (max err ") +
                          std::to_string(maxErr) + ") on " + dp.deviceName};
}

}  // namespace qorvix::vulkan
